import { Rank, Player, Quest, QuestCategory, Item, Dungeon, ShopItem, ShadowSoldier, ShadowExpedition, ActivityDay, HunterSkill, HunterAchievement, WorldBoss, HunterSaga } from './types';

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'i1',
    name: 'Shadow Sovereign Visor',
    description: 'A dark plate that enhances perception and focus.',
    rarity: 'Epic',
    slot: 'head',
    icon: 'visibility',
    priceGold: 4500,
    priceEssence: 35,
    stats: { VIT: 5, WIS: 4 },
    effect: '+10% Focus Duration'
  },
  {
    id: 'i2',
    name: "Nightwalker's Dual Daggers",
    description: 'Twin blades forged from condensed mana of the Shadow Domain.',
    rarity: 'Legendary',
    slot: 'weapon',
    icon: 'swords',
    priceGold: 12000,
    priceEssence: 90,
    stats: { STR: 14, AGI: 10 },
    effect: '+25% Strike Velocity'
  },
  {
    id: 'i3',
    name: "Monarch's Chestplate",
    description: 'Blackened titanium forged with shadow monarch seals.',
    rarity: 'Epic',
    slot: 'chest',
    icon: 'shield',
    priceGold: 7000,
    priceEssence: 50,
    stats: { VIT: 12, STR: 4 }
  },
  {
    id: 'i4',
    name: 'Boots of the Shadow Assassin',
    description: 'Silent treaders that grant sudden bursts of swiftness.',
    rarity: 'Rare',
    slot: 'feet',
    icon: 'steps',
    priceGold: 2200,
    priceEssence: 15,
    stats: { AGI: 8 }
  },
  {
    id: 'i5',
    name: 'Ring of Sovereign Dominance',
    description: 'An ancient relic radiating aura that bends willpower.',
    rarity: 'Legendary',
    slot: 'accessory',
    icon: 'diamond',
    priceGold: 15000,
    priceEssence: 120,
    stats: { INT: 10, CHA: 12, WIS: 6 }
  }
];

export const INITIAL_PLAYER: Player = {
  name: "Cazador Despertado",
  title: "The Weakest Hunter",
  level: 1,
  xp: 0,
  maxXp: 1000,
  mp: 100,
  maxMp: 100,
  rank: Rank.E,
  gold: 0,
  essenceStones: 0,
  statPoints: 0,
  streakDays: 0,
  lastActiveDate: new Date().toISOString().split('T')[0],
  soundEnabled: true,
  attributes: {
    str: { name: 'Fuerza', code: 'STR', value: 10, icon: 'fitness_center', color: 'text-red-500', bonusText: '+2.0% Potencia física' },
    int: { name: 'Inteligencia', code: 'INT', value: 10, icon: 'psychology', color: 'text-blue-400', bonusText: '+2.0% Capacidad cognitiva' },
    vit: { name: 'Vitalidad', code: 'VIT', value: 10, icon: 'favorite', color: 'text-emerald-500', bonusText: '+3.0% Resistencia y energía' },
    agi: { name: 'Agilidad', code: 'AGI', value: 10, icon: 'bolt', color: 'text-yellow-500', bonusText: '+2.0% Velocidad de ejecución' },
    wis: { name: 'Sabiduría', code: 'WIS', value: 10, icon: 'auto_awesome', color: 'text-purple-400', bonusText: '+2.0% Claridad mental' },
    cha: { name: 'Carisma', code: 'CHA', value: 10, icon: 'stars', color: 'text-pink-400', bonusText: '+2.0% Presencia e influencia' },
  },
  equipped: {
    head: null,
    chest: null,
    pants: null,
    feet: null,
    gloves: null,
    weapon: null,
    accessory: null,
  },
  inventory: [],
  titlesUnlocked: [
    "The Weakest Hunter"
  ],
  avatarId: 'monarch-shadow',
  avatarFrame: 'frame-e',
  hunterClass: 'Monarca'
};

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'q1',
    title: 'Superar el Límite: 50 Flexiones & 50 Sentadillas',
    description: 'Entrenamiento físico de acondicionamiento muscular para templar el cuerpo.',
    rank: Rank.E,
    category: 'fitness',
    rewards: { xp: 180, gold: 120, essenceStones: 5 },
    completed: false,
    isDaily: true,
    targetCount: 100,
    currentCount: 0,
    unit: 'reps',
    createdAt: new Date().toISOString()
  },
  {
    id: 'q2',
    title: 'Estudio de Alto Impacto: 45m Lectura Técnica',
    description: 'Absorber conceptos profundos sin interrupciones para elevar la Inteligencia.',
    rank: Rank.B,
    category: 'intellect',
    rewards: { xp: 350, gold: 240, essenceStones: 12, statPoints: 1 },
    completed: false,
    isDaily: true,
    targetCount: 45,
    currentCount: 0,
    unit: 'min',
    createdAt: new Date().toISOString()
  },
  {
    id: 'q3',
    title: 'Silencio Mental: 15m Meditación Profunda',
    description: 'Recuperación de maná mental y reducción de cortisol matutino.',
    rank: Rank.E,
    category: 'mindfulness',
    rewards: { xp: 120, gold: 80, essenceStones: 3 },
    completed: false,
    isDaily: true,
    targetCount: 15,
    currentCount: 0,
    unit: 'min',
    createdAt: new Date().toISOString()
  },
  {
    id: 'q4',
    title: 'Planificación Estratégica: Revisión de Objetivos',
    description: 'Estructurar las batallas del día y optimizar el tiempo del cazador.',
    rank: Rank.C,
    category: 'discipline',
    rewards: { xp: 220, gold: 150, essenceStones: 8 },
    completed: false,
    isDaily: true,
    targetCount: 1,
    currentCount: 0,
    unit: 'sesión',
    createdAt: new Date().toISOString()
  },
  {
    id: 'q5',
    title: 'Hidratación de Maná Puro: 2.5 Litros de Agua',
    description: 'Mantener la circulación celular y vitalidad óptima durante todo el día.',
    rank: Rank.E,
    category: 'habit',
    rewards: { xp: 150, gold: 100, essenceStones: 4 },
    completed: false,
    isDaily: true,
    targetCount: 2500,
    currentCount: 0,
    unit: 'ml',
    createdAt: new Date().toISOString()
  },
  {
    id: 'q6',
    title: 'Desintoxicación de Dopamina: 60m Sin Redes Sociales',
    description: 'Purga de estímulos superficiales para restaurar los receptores de dopamina.',
    rank: Rank.B,
    category: 'discipline',
    rewards: { xp: 380, gold: 280, essenceStones: 14, statPoints: 1 },
    completed: false,
    isDaily: true,
    targetCount: 60,
    currentCount: 0,
    unit: 'min',
    createdAt: new Date().toISOString()
  },
  {
    id: 'q7',
    title: 'Marcha del Monarca: 8,000 Pasos Diarios',
    description: 'Actividad física continua para acelerar la regeneración y quemar fatiga.',
    rank: Rank.D,
    category: 'fitness',
    rewards: { xp: 200, gold: 140, essenceStones: 6 },
    completed: false,
    isDaily: true,
    targetCount: 8000,
    currentCount: 0,
    unit: 'pasos',
    createdAt: new Date().toISOString()
  },
  {
    id: 'q8',
    title: 'Sueño Regenerativo: 7.5 Horas de Descanso',
    description: 'Dormir temprano en oscuridad completa para regenerar el 100% del HP y MP.',
    rank: Rank.C,
    category: 'habit',
    rewards: { xp: 250, gold: 180, essenceStones: 8 },
    completed: false,
    isDaily: true,
    targetCount: 8,
    currentCount: 0,
    unit: 'horas',
    createdAt: new Date().toISOString()
  }
];

export interface HabitPreset {
  id: string;
  title: string;
  description: string;
  category: QuestCategory;
  rank: Rank;
  targetCount: number;
  unit: string;
  attributeTarget: string;
  xpReward: number;
  goldReward: number;
  essenceReward: number;
  icon: string;
}

export const HABIT_PRESETS: HabitPreset[] = [
  {
    id: 'preset_jinwoo_workout',
    title: 'Entrenamiento del Monarca: 100 Flexiones, 100 Sentadillas, 100 Abdominales',
    description: 'La legendaria rutina diaria de fuerza que forjó al cazador más fuerte de la historia.',
    category: 'fitness',
    rank: Rank.A,
    targetCount: 300,
    unit: 'reps totales',
    attributeTarget: 'STR',
    xpReward: 850,
    goldReward: 1200,
    essenceReward: 25,
    icon: 'fitness_center',
  },
  {
    id: 'preset_cold_shower',
    title: 'Ducha de Agua Fría: Templanza Ártica',
    description: '2 minutos de choque térmico para activar el sistema nervioso y fortalecer la voluntad.',
    category: 'discipline',
    rank: Rank.D,
    targetCount: 2,
    unit: 'minutos',
    attributeTarget: 'VIT',
    xpReward: 180,
    goldReward: 140,
    essenceReward: 6,
    icon: 'ac_unit',
  },
  {
    id: 'preset_deep_code',
    title: 'Bloque de Deep Work: 60m Enfoque Absoluto',
    description: 'Concentración total en un solo proyecto de alto valor sin multitarea.',
    category: 'intellect',
    rank: Rank.B,
    targetCount: 60,
    unit: 'minutos',
    attributeTarget: 'INT',
    xpReward: 420,
    goldReward: 320,
    essenceReward: 15,
    icon: 'terminal',
  },
  {
    id: 'preset_stoic_journal',
    title: 'Diario del Cazador: Reflexión y Gratitud',
    description: 'Escribir 3 victorias del día y lecciones aprendidas para cultivar Sabiduría.',
    category: 'mindfulness',
    rank: Rank.E,
    targetCount: 1,
    unit: 'entrada',
    attributeTarget: 'WIS',
    xpReward: 150,
    goldReward: 100,
    essenceReward: 4,
    icon: 'menu_book',
  },
  {
    id: 'preset_clean_sanctuary',
    title: 'Purificación del Espacio: Orden del Santuario',
    description: 'Limpiar y organizar tu escritorio o habitación para despejar la mente.',
    category: 'discipline',
    rank: Rank.E,
    targetCount: 15,
    unit: 'minutos',
    attributeTarget: 'WIS',
    xpReward: 160,
    goldReward: 110,
    essenceReward: 5,
    icon: 'cleaning_services',
  },
  {
    id: 'preset_no_sugar',
    title: 'Dieta Limpia de Maná: Cero Azúcar Añadido',
    description: 'Eliminar ultraprocesados y azúcar refinada durante 24 horas continuas.',
    category: 'habit',
    rank: Rank.C,
    targetCount: 1,
    unit: 'día limpio',
    attributeTarget: 'VIT',
    xpReward: 260,
    goldReward: 200,
    essenceReward: 10,
    icon: 'restaurant',
  },
];

export const INITIAL_DUNGEONS: Dungeon[] = [
  {
    id: 'dungeon_1',
    title: 'The Deep Work Crypt: 25-Minute Focus Raid',
    description: 'Sombra de concentración extrema. Sin redes, sin pestañas irrelevantes. Vence a los demonios de la distracción.',
    rank: Rank.B,
    icon: 'hourglass_top',
    type: 'focus_timer',
    durationMinutes: 25,
    rewards: {
      xp: 450,
      gold: 320,
      essenceStones: 15,
      itemDrop: {
        id: 'drop_1',
        name: 'Gloves of Pure Focus',
        description: 'Gloves that stabilize mana manipulation during deep tasks.',
        rarity: 'Rare',
        slot: 'gloves',
        icon: 'back_hand',
        priceGold: 1800,
        stats: { INT: 6, WIS: 4 }
      }
    },
    completed: false
  },
  {
    id: 'dungeon_2',
    title: 'Trial of the Iron Monarch: Workout Dungeon',
    description: 'Mazmorra de fuerza física. Completa las series exigidas para purificar la debilidad de la carne.',
    rank: Rank.A,
    icon: 'fitness_center',
    type: 'fitness_raid',
    durationMinutes: 30,
    tasks: [
      { id: 't1', title: 'Push-ups (Flexiones)', target: 60, current: 0, unit: 'reps', completed: false },
      { id: 't2', title: 'Bodyweight Squats (Sentadillas)', target: 80, current: 0, unit: 'reps', completed: false },
      { id: 't3', title: 'Core Planks (Plancha abdominal)', target: 180, current: 0, unit: 'seg', completed: false },
      { id: 't4', title: 'Burpees explosivos', target: 25, current: 0, unit: 'reps', completed: false },
    ],
    rewards: {
      xp: 850,
      gold: 600,
      essenceStones: 25,
      titleUnlock: "Iron Vanguard",
      itemDrop: {
        id: 'drop_2',
        name: 'Armor of the Unbroken Iron',
        description: 'Heavy plate that turns physical strain into raw power.',
        rarity: 'Epic',
        slot: 'chest',
        icon: 'shield',
        priceGold: 6000,
        stats: { STR: 10, VIT: 12 }
      }
    },
    completed: false
  },
  {
    id: 'dungeon_3',
    title: 'Sanctum of Eternal Intellect: 50-Min Mastery Sprint',
    description: 'Incursión de alto rango para aprendizaje complejo, lectura técnica densa o resolución de problemas difíciles.',
    rank: Rank.S,
    icon: 'psychology',
    type: 'study_trial',
    durationMinutes: 50,
    rewards: {
      xp: 1400,
      gold: 1200,
      essenceStones: 45,
      itemDrop: {
        id: 'drop_3',
        name: 'Amulet of the Shadow Sovereign',
        description: 'A radiant artifact that doubles mana regeneration.',
        rarity: 'Legendary',
        slot: 'accessory',
        icon: 'diamond',
        priceGold: 14000,
        stats: { INT: 15, WIS: 12, CHA: 8 }
      }
    },
    completed: false
  }
];

export const SHOP_CATALOG: ShopItem[] = [
  {
    id: 'shop_1',
    name: 'Demon King’s Dagger',
    description: 'Forged from the lightning core of Baran, sparks with blue electricity.',
    rarity: 'Legendary',
    slot: 'weapon',
    icon: 'swords',
    priceGold: 9500,
    priceEssence: 80,
    stats: { STR: 18, AGI: 14 },
    effect: '+30% Critical Output',
    featured: true
  },
  {
    id: 'shop_2',
    name: 'Shadow Commander Cuirass',
    description: 'Impenetrable black cuirass with dark aura tendrils.',
    rarity: 'Epic',
    slot: 'chest',
    icon: 'shield',
    priceGold: 6200,
    priceEssence: 45,
    stats: { VIT: 14, STR: 6 },
    featured: true
  },
  {
    id: 'shop_3',
    name: 'Greaves of the Abyssal Walker',
    description: 'Padded reinforced greaves made of monarch alloy.',
    rarity: 'Rare',
    slot: 'pants',
    icon: 'layers',
    priceGold: 2800,
    priceEssence: 20,
    stats: { VIT: 6, AGI: 5 }
  },
  {
    id: 'shop_4',
    name: 'Gauntlets of the Iron Berserker',
    description: 'Heavy spikes that crush obstacle tasks with ease.',
    rarity: 'Rare',
    slot: 'gloves',
    icon: 'back_hand',
    priceGold: 2400,
    priceEssence: 18,
    stats: { STR: 7, VIT: 3 }
  },
  {
    id: 'shop_5',
    name: 'Tears of the Divine Healer (Elixir)',
    description: 'Consumable elixir that clears mental fog and awards +800 XP instantly.',
    rarity: 'Epic',
    slot: 'consumable',
    icon: 'local_drink',
    priceGold: 1400,
    priceEssence: 10,
    stats: {},
    consumableType: 'xp',
    consumableValue: 800
  },
  {
    id: 'shop_6',
    name: 'Stat Resonance Crystal',
    description: 'A glowing crystalline core that directly awards +1 Permanent Stat Point.',
    rarity: 'Mythic',
    slot: 'consumable',
    icon: 'category',
    priceGold: 8000,
    priceEssence: 65,
    stats: {},
    consumableType: 'stat_point',
    consumableValue: 1,
    featured: true
  },
  {
    id: 'shop_7',
    name: 'Essence Stone Pouch',
    description: 'Contains 50 raw Essence Stones extracted from high-rank gates.',
    rarity: 'Rare',
    slot: 'consumable',
    icon: 'toll',
    priceGold: 3000,
    stats: {},
    consumableType: 'essence',
    consumableValue: 50
  },
  {
    id: 'shop_streak_shield',
    name: 'Poción de Preservación del Tiempo (Streak Shield)',
    description: 'Protege tu racha diaria activa si tienes un día de emergencia o descanso forzoso.',
    rarity: 'Epic',
    slot: 'consumable',
    icon: 'shield_moon',
    priceGold: 4500,
    priceEssence: 30,
    stats: {},
    consumableType: 'xp',
    consumableValue: 500,
    effect: 'Protección de Racha + 500 XP'
  },
  {
    id: 'shop_kasaka_fang',
    name: 'Colmillo Venenoso de Rasaka',
    description: 'Daga rápida extraída de la serpiente gigante del pantano. Aplica parálisis a la fatiga.',
    rarity: 'Epic',
    slot: 'weapon',
    icon: 'colorize',
    priceGold: 5800,
    priceEssence: 35,
    stats: { AGI: 15, STR: 8 },
    effect: '+20% Velocidad de Tareas'
  },
  {
    id: 'shop_orb_avarice',
    name: 'Orbe de la Avaricia',
    description: 'Orbe carmesí de Vulcano que duplica el daño mágico y el poder del intelecto.',
    rarity: 'Legendary',
    slot: 'accessory',
    icon: 'lens',
    priceGold: 16000,
    priceEssence: 120,
    stats: { INT: 28, WIS: 20 },
    effect: '+100% Daño de Habilidades de Mago'
  },
  {
    id: 'shop_kamish_wrath',
    name: 'Ira de Kamish (Dagas Gemelas)',
    description: 'Las dagas más afiladas del mundo, forjadas con los colmillos del dragón más temible de la humanidad.',
    rarity: 'Mythic',
    slot: 'weapon',
    icon: 'swords',
    priceGold: 35000,
    priceEssence: 250,
    stats: { STR: 40, AGI: 35 },
    effect: '+60% Daño Crítico Total',
    featured: true
  }
];

export const INITIAL_SHADOW_ARMY: ShadowSoldier[] = [
  {
    id: 'shadow_igris',
    name: 'Igris el Rojo Sangre',
    title: 'Comandante de la Guardia Real',
    rank: Rank.S,
    icon: 'swords',
    level: 1,
    combatPower: 45000,
    bonusDescription: '+15% Multiplicador de Ataque & +10% Velocidad de Enfoque',
    unlocked: true,
    unlockCondition: 'Desbloqueado por defecto al Despertar.',
  },
  {
    id: 'shadow_tank',
    name: 'Tank',
    title: 'Líder de los Osos de Hielo',
    rank: Rank.A,
    icon: 'pets',
    level: 1,
    combatPower: 28000,
    bonusDescription: '+20% Vitalidad & Reducción de fatiga en entrenamientos',
    unlocked: true,
    unlockCondition: 'Alcanza el Nivel 5 o completa 5 incursiones.',
  },
  {
    id: 'shadow_iron',
    name: 'Iron',
    title: 'Caballero del Escudo Gigante',
    rank: Rank.A,
    icon: 'shield',
    level: 1,
    combatPower: 32000,
    bonusDescription: '+15% Defensa & Protección contra penalizaciones',
    unlocked: false,
    unlockCondition: 'Supera 1 sesión de la Zona de Penalización.',
  },
  {
    id: 'shadow_beru',
    name: 'Beru',
    title: 'Rey de las Sombras Hormiga',
    rank: Rank.NATIONAL,
    icon: 'military_tech',
    level: 1,
    combatPower: 95000,
    bonusDescription: '+40% Poder de Combate Total & +25% Ganancia de Oro',
    unlocked: false,
    unlockCondition: 'Alcanza el Nivel 25 o Rango S en el Sistema.',
  },
  {
    id: 'shadow_kaisel',
    name: 'Kaisel',
    title: 'Wyvern de las Sombras Abisales',
    rank: Rank.S,
    icon: 'flight',
    level: 1,
    combatPower: 60000,
    bonusDescription: '+50% Velocidad de Expediciones Pasivas',
    unlocked: false,
    unlockCondition: 'Completa 10 Misiones Diarias consecutivas.',
  },
];

export const INITIAL_SHADOW_EXPEDITIONS: ShadowExpedition[] = [
  {
    id: 'exp_1',
    title: 'Patrulla de la Puerta E-Rank',
    gateRank: Rank.E,
    durationMinutes: 5,
    assignedShadowId: null,
    startedAt: null,
    rewards: { xp: 350, gold: 600, essenceStones: 5 },
    status: 'idle',
  },
  {
    id: 'exp_2',
    title: 'Asalto a las Minas de Duendes C-Rank',
    gateRank: Rank.C,
    durationMinutes: 15,
    assignedShadowId: null,
    startedAt: null,
    rewards: { xp: 1200, gold: 2200, essenceStones: 18 },
    status: 'idle',
  },
  {
    id: 'exp_3',
    title: 'Incursión en la Torre Demoníaca A-Rank',
    gateRank: Rank.A,
    durationMinutes: 30,
    assignedShadowId: null,
    startedAt: null,
    rewards: { xp: 3800, gold: 6500, essenceStones: 45 },
    status: 'idle',
  },
  {
    id: 'exp_4',
    title: 'Cámara del Monarca de los Dragones S-Rank',
    gateRank: Rank.S,
    durationMinutes: 60,
    assignedShadowId: null,
    startedAt: null,
    rewards: { xp: 10000, gold: 18000, essenceStones: 120 },
    status: 'idle',
  },
];

export const INITIAL_ACTIVITY_HISTORY: ActivityDay[] = [];

export const INITIAL_SKILLS: HunterSkill[] = [
  {
    id: 'skill_rulers_authority',
    name: "Autoridad del Gobernante",
    title: "Telequinesis del Alma",
    type: 'active',
    description: "Manipula la materia sin tocarla. Otorga +25% de eficiencia en sesiones de Deep Work y reduce la fatiga mental.",
    level: 1,
    maxLevel: 5,
    icon: 'psychology',
    effect: '+25% Multiplicador de XP en Mazmorras de Enfoque',
    unlocked: true,
    unlockLevel: 1,
    costEssence: 20,
  },
  {
    id: 'skill_shadow_extraction',
    name: "Extracción de Sombras",
    title: "Comandante de los Muertos",
    type: 'passive',
    description: "El poder del Monarca para extraer la fuerza vital de los desafíos superados. Incrementa el botín de oro y esencias.",
    level: 1,
    maxLevel: 5,
    icon: 'groups',
    effect: '+30% Oro & +20% Probabilidad de caída de piedras de esencia',
    unlocked: true,
    unlockLevel: 3,
    costEssence: 35,
  },
  {
    id: 'skill_bloodlust',
    name: "Sed de Sangre (Intimidación)",
    title: "Aura Asesina",
    type: 'buff',
    description: "Irradia un aura paralizante sobre las dudas y la procrastinación. Potencia instantáneamente el daño a Jefes de Mazmorra.",
    level: 1,
    maxLevel: 5,
    icon: 'local_fire_department',
    effect: '+50% Daño en Asaltos a Jefes Semanales',
    unlocked: false,
    unlockLevel: 6,
    costEssence: 50,
  },
  {
    id: 'skill_sprint',
    name: "Sprint de Sombras",
    title: "Velocidad Extrema",
    type: 'active',
    description: "Aumenta la agilidad corporal en un 40%. Facilita el cumplimiento de series físicas y reduce el tiempo necesario.",
    level: 1,
    maxLevel: 5,
    icon: 'directions_run',
    effect: '+35% Velocidad de regeneración y bono de atributos AGI',
    unlocked: false,
    unlockLevel: 10,
    costEssence: 75,
  },
  {
    id: 'skill_monarchs_domain',
    name: "Dominio del Monarca",
    title: "Territorio de Sombras",
    type: 'buff',
    description: "Expande un manto de oscuridad absoluta. Todas las sombras del ejército ganan +50% de poder de combate dentro de la zona.",
    level: 1,
    maxLevel: 5,
    icon: 'shield_moon',
    effect: '+60% Eficacia en expediciones de sombra pasivas',
    unlocked: false,
    unlockLevel: 15,
    costEssence: 120,
  },
];

export const INITIAL_ACHIEVEMENTS: HunterAchievement[] = [
  {
    id: 'ach_awaken',
    title: 'El Despertar del Cazador',
    description: 'Inicia el protocolo del Sistema y registra tu nombre en el registro.',
    icon: 'auto_awesome',
    category: 'combat',
    progress: 1,
    target: 1,
    completed: true,
    claimed: true,
    rewards: { xp: 500, gold: 1000, essenceStones: 10, titleReward: 'Awakened Novice' },
  },
  {
    id: 'ach_streak_3',
    title: 'Disciplina de Hierro',
    description: 'Mantén una racha activa de cumplimiento de al menos 3 días.',
    icon: 'local_fire_department',
    category: 'habits',
    progress: 3,
    target: 3,
    completed: true,
    claimed: false,
    rewards: { xp: 1200, gold: 2500, essenceStones: 25, titleReward: 'Iron Will' },
  },
  {
    id: 'ach_streak_7',
    title: 'La Forja del Guerrero',
    description: 'Completa 7 días ininterrumpidos de misiones diarias.',
    icon: 'whatshot',
    category: 'habits',
    progress: 3,
    target: 7,
    completed: false,
    claimed: false,
    rewards: { xp: 3000, gold: 6000, essenceStones: 60, titleReward: 'Unshakable' },
  },
  {
    id: 'ach_streak_14',
    title: 'Voluntad Inquebrantable',
    description: 'Mantén 14 días consecutivos forjando hábitos sin romper la racha.',
    icon: 'military_tech',
    category: 'habits',
    progress: 3,
    target: 14,
    completed: false,
    claimed: false,
    rewards: { xp: 7500, gold: 15000, essenceStones: 120, titleReward: 'Unbreakable Spirit' },
  },
  {
    id: 'ach_streak_30',
    title: 'Monarca de la Autodisciplina',
    description: 'Alcanza la cumbre: 30 días ininterrumpidos de transformación personal.',
    icon: 'crown',
    category: 'habits',
    progress: 3,
    target: 30,
    completed: false,
    claimed: false,
    rewards: { xp: 20000, gold: 50000, essenceStones: 300, titleReward: 'Ascended Monarch' },
  },
  {
    id: 'ach_dungeon_master',
    title: 'Purificador de Puertas',
    description: 'Supera con éxito 5 incursiones de mazmorra o sesiones de Deep Work.',
    icon: 'door_open',
    category: 'dungeons',
    progress: 2,
    target: 5,
    completed: false,
    claimed: false,
    rewards: { xp: 2200, gold: 4500, essenceStones: 40, titleReward: 'Dungeon Conqueror' },
  },
  {
    id: 'ach_shadow_commander',
    title: 'Comandante de la Muerte',
    description: 'Desbloquea y comanda al menos 3 soldados en el Ejército de Sombras.',
    icon: 'groups',
    category: 'shadows',
    progress: 2,
    target: 3,
    completed: false,
    claimed: false,
    rewards: { xp: 4000, gold: 8000, essenceStones: 80, titleReward: 'Shadow Commander' },
  },
  {
    id: 'ach_combat_power_100k',
    title: 'Trascendencia de Rango S',
    description: 'Alcanza más de 100,000 puntos de Poder de Combate Total.',
    icon: 'military_tech',
    category: 'combat',
    progress: 42000,
    target: 100000,
    completed: false,
    claimed: false,
    rewards: { xp: 10000, gold: 20000, essenceStones: 150, titleReward: 'The Shadow Monarch' },
  },
];

export const INITIAL_WORLD_BOSSES: WorldBoss[] = [
  {
    id: 'boss_cerberus',
    name: 'Cerbero, Perro Guardián del Inframundo',
    title: 'Bestia Guardiana de la Puerta Roja',
    rank: Rank.A,
    icon: 'pets',
    maxHp: 120000,
    currentHp: 120000,
    level: 25,
    damageLog: [],
    rewards: {
      xp: 8000,
      gold: 15000,
      essenceStones: 80,
      titleUnlock: 'Gatekeeper Slayer',
      exclusiveItem: {
        id: 'drop_cerberus_fang',
        name: 'Colmillo Ígneo de Cerbero',
        description: 'Imbuido con fuego infernal. Acelera la quema de calorías y la agilidad.',
        rarity: 'Epic',
        slot: 'weapon',
        icon: 'swords',
        priceGold: 8500,
        stats: { STR: 16, AGI: 14 },
        effect: '+25% Daño Físico'
      },
    },
    defeated: false,
  },
  {
    id: 'boss_igris_trial',
    name: 'Igris el Caballero Rojo',
    title: 'Guardián del Trono Abandonado',
    rank: Rank.S,
    icon: 'swords',
    maxHp: 250000,
    currentHp: 185000,
    level: 40,
    damageLog: [
      { hunter: 'Sung Jin-Woo', damage: 35000, timestamp: 'Hace 2 horas' },
      { hunter: 'Sung Jin-Woo', damage: 30000, timestamp: 'Hace 5 horas' },
    ],
    rewards: {
      xp: 15000,
      gold: 30000,
      essenceStones: 150,
      titleUnlock: 'Demon Castle Slayer',
      exclusiveItem: {
        id: 'drop_igris_sword',
        name: 'Espada Larga del Caballero Rojo',
        description: 'Empapada en la sangre de mil batallas. Corta la fatiga instantáneamente.',
        rarity: 'Legendary',
        slot: 'weapon',
        icon: 'swords',
        priceGold: 18000,
        stats: { STR: 25, AGI: 18 },
        effect: '+30% Daño Crítico',
      },
    },
    defeated: false,
  },
  {
    id: 'boss_baran',
    name: 'Baran el Rey de los Demonios',
    title: 'Soberano de las Llamas Blancas del Piso 100',
    rank: Rank.S,
    icon: 'bolt',
    maxHp: 450000,
    currentHp: 450000,
    level: 60,
    damageLog: [],
    rewards: {
      xp: 30000,
      gold: 60000,
      essenceStones: 300,
      titleUnlock: 'Monarch of White Flames',
      exclusiveItem: {
        id: 'drop_baran_ring',
        name: 'Anillo del Rey Demonio',
        description: 'Libera rayos de maná concentrado cada vez que completas un bloque de estudio.',
        rarity: 'Legendary',
        slot: 'accessory',
        icon: 'diamond',
        priceGold: 26000,
        stats: { INT: 30, WIS: 22 },
        effect: '+45% Eficacia Intelectual'
      },
    },
    defeated: false,
  },
  {
    id: 'boss_ant_king',
    name: 'Rey Hormiga de la Isla Jeju (Beru Despertado)',
    title: 'Monstruo Mutante de Rango Nacional',
    rank: Rank.NATIONAL,
    icon: 'pest_control',
    maxHp: 800000,
    currentHp: 800000,
    level: 75,
    damageLog: [],
    rewards: {
      xp: 50000,
      gold: 100000,
      essenceStones: 500,
      titleUnlock: 'Savior of Humanity',
      exclusiveItem: {
        id: 'drop_ant_king_crown',
        name: 'Corona del Monarca Depredador',
        description: 'La presencia de una calamidad viva. Atrae poder ilimitado.',
        rarity: 'Mythic',
        slot: 'head',
        icon: 'military_tech',
        priceGold: 50000,
        stats: { STR: 35, INT: 35, VIT: 35, AGI: 35, WIS: 35, CHA: 35 },
        effect: '+50% All Stats & Aura de Miedo',
      },
    },
    defeated: false,
  },
  {
    id: 'boss_kamish',
    name: 'Kamish el Dragón Antiguo',
    title: 'La Peor Calamidad en la Historia Humana',
    rank: Rank.NATIONAL,
    icon: 'local_fire_department',
    maxHp: 1500000,
    currentHp: 1500000,
    level: 100,
    damageLog: [],
    rewards: {
      xp: 100000,
      gold: 250000,
      essenceStones: 1200,
      titleUnlock: 'Dragon Slayer of the Apocalypse',
      exclusiveItem: {
        id: 'drop_kamish_rune',
        name: 'Runa del Aliento del Dragón',
        description: 'La esencia pura del dragón de la destrucción. Otorga invencibilidad ante la procrastinación.',
        rarity: 'Mythic',
        slot: 'accessory',
        icon: 'stars',
        priceGold: 80000,
        stats: { STR: 50, INT: 50, VIT: 50, AGI: 50, WIS: 50, CHA: 50 },
        effect: '+100% XP & Inmunidad a la Fatiga'
      },
    },
    defeated: false,
  },
];

export const INITIAL_SAGAS: HunterSaga[] = [
  {
    id: 'saga_double_awakening',
    title: 'Arco del Doble Despertar',
    codeName: 'SAGA-01: THE REBIRTH',
    subtitle: 'Reconfiguración Neuronal en 21 Días',
    description: 'La forja inicial del cazador. Establece los cimientos inquebrantables de tus rutinas matutinas y nocturnas sin fallar un solo día.',
    lore: 'En el templo de Cartenon, solo aquellos que obedecieron los mandamientos del Sistema sobrevivieron a la purga. 21 días de disciplina absoluta reescribirán tu fisiología.',
    rankRequirement: Rank.E,
    durationDays: 21,
    currentDay: 1,
    category: 'discipline',
    bannerColor: 'from-blue-900/60 to-indigo-950/80',
    icon: 'military_tech',
    active: true,
    completed: false,
    milestones: [
      {
        day: 7,
        title: 'Fase I: Ruptura de la Inercia (Día 7)',
        description: 'Mantén una racha de 7 días completando al menos 2 misiones diarias.',
        requirement: '7 Días de Racha Consecutiva',
        targetAmount: 7,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 2500,
          gold: 5000,
          essenceStones: 30,
          statPoints: 2,
          titleReward: 'Iniciado Despierto'
        }
      },
      {
        day: 14,
        title: 'Fase II: El Canal de Maná (Día 14)',
        description: 'Supera 14 días consecutivos y completa 20 misiones acumuladas.',
        requirement: '14 Días y 20 Misiones',
        targetAmount: 14,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 6000,
          gold: 12000,
          essenceStones: 60,
          statPoints: 4,
          titleReward: 'Forjador de Hábitos'
        }
      },
      {
        day: 21,
        title: 'Fase III: Neuroplasticidad Sellada (Día 21)',
        description: '21 días ininterrumpidos. Tu cerebro ha fijado el nuevo estándar de vida.',
        requirement: '21 Días de Racha Perfecta',
        targetAmount: 21,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 15000,
          gold: 30000,
          essenceStones: 150,
          statPoints: 6,
          titleReward: 'Monarca Reencarnado'
        }
      }
    ],
    finalReward: {
      xp: 25000,
      gold: 50000,
      essenceStones: 300,
      exclusiveTitle: 'Cazador que Desafió a la Muerte',
      exclusiveItem: {
        id: 'item_reborn_mantle',
        name: 'Manto del Doble Despertar',
        description: 'Capa legendaria infundida con la persistencia inquebrantable de 21 días de superación.',
        rarity: 'Legendary',
        slot: 'chest',
        icon: 'shield',
        priceGold: 40000,
        stats: { VIT: 20, WIS: 15, STR: 15 },
        effect: '+25% de XP en todas las misiones matutinas'
      }
    }
  },
  {
    id: 'saga_demon_castle',
    title: 'Arco del Castillo Demoníaco',
    codeName: 'SAGA-02: INFERNAL PURGE',
    subtitle: 'Dominio Físico y Mental de 60 Días',
    description: 'Una expedición de 2 meses ascendiendo los 100 pisos del castillo demoníaco mediante el trabajo profundo, la lectura y el entrenamiento físico implacable.',
    lore: 'Para fabricar el Elixir de la Vida y sanar cualquier debilidad de tu cuerpo, debes ascender los pisos más oscuros sin abandonar la batalla.',
    rankRequirement: Rank.C,
    durationDays: 60,
    currentDay: 1,
    category: 'physical',
    bannerColor: 'from-purple-900/60 to-rose-950/80',
    icon: 'castle',
    active: false,
    completed: false,
    milestones: [
      {
        day: 15,
        title: 'Piso 25: Purga de Demonios Menores (Día 15)',
        description: 'Acumula 15 días activos y 10 horas de concentración profunda.',
        requirement: '15 Días y 10h Foco',
        targetAmount: 15,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 8000,
          gold: 15000,
          essenceStones: 80,
          statPoints: 3,
        }
      },
      {
        day: 30,
        title: 'Piso 50: La Forja de Vulkan (Día 30)',
        description: 'Alcanza el primer mes completo de la campaña y 50 misiones superadas.',
        requirement: '30 Días de Campaña',
        targetAmount: 30,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 18000,
          gold: 35000,
          essenceStones: 180,
          statPoints: 6,
          titleReward: 'Conquistador de Vulkan'
        }
      },
      {
        day: 45,
        title: 'Piso 75: Las Tierras Nevadas de Metus (Día 45)',
        description: '45 días de racha implacable contra la pereza invernal.',
        requirement: '45 Días de Constancia',
        targetAmount: 45,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 30000,
          gold: 60000,
          essenceStones: 300,
          statPoints: 8,
        }
      },
      {
        day: 60,
        title: 'Piso 100: El Trono del Rey Baran (Día 60)',
        description: '60 días de ascensión. Derrota al Rey de las Llamas Blancas con tu nueva disciplina.',
        requirement: '60 Días de Ascensión Completa',
        targetAmount: 60,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 60000,
          gold: 120000,
          essenceStones: 600,
          statPoints: 12,
          titleReward: 'Soberano de las Llamas Blancas'
        }
      }
    ],
    finalReward: {
      xp: 80000,
      gold: 180000,
      essenceStones: 800,
      exclusiveTitle: 'Rey del Castillo Demoníaco',
      exclusiveItem: {
        id: 'item_demon_king_daggers',
        name: 'Dagas del Rey Demonio Baran',
        description: 'Armas gemelas imbuidas de relámpagos demoníacos. Multiplican el daño de tus hábitos un 40%.',
        rarity: 'Mythic',
        slot: 'weapon',
        icon: 'swords',
        priceGold: 90000,
        stats: { STR: 35, AGI: 30, INT: 20 },
        effect: '+30% Daño a Jefes de Hábitos y Doble Oro'
      }
    }
  },
  {
    id: 'saga_jeju_island',
    title: 'Arco de la Isla Jeju (Raid Rango S)',
    codeName: 'SAGA-03: JEJU EXTERMINATION',
    subtitle: 'La Máxima Metamorfosis Humana en 90 Días',
    description: 'La campaña definitiva de 3 meses para erradicar cualquier rastro de debilidad, procrastinación y autoengaño.',
    lore: 'La humanidad intentó recuperar la isla 3 veces y fracasó. Solo el surgimiento del verdadero Monarca de las Sombras podrá limpiar el nido de hormigas.',
    rankRequirement: Rank.A,
    durationDays: 90,
    currentDay: 1,
    category: 'mastery',
    bannerColor: 'from-amber-950/60 to-red-950/90',
    icon: 'coronavirus',
    active: false,
    completed: false,
    milestones: [
      {
        day: 30,
        title: 'Infiltración en la Costa de Jeju (Día 30)',
        description: 'Primer mes de exterminio de malos hábitos.',
        requirement: '30 Días de Racha Rango S',
        targetAmount: 30,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 25000,
          gold: 50000,
          essenceStones: 250,
          statPoints: 5,
        }
      },
      {
        day: 60,
        title: 'Brecha en el Túnel de la Reina (Día 60)',
        description: '60 días de transformación física y mental imparable.',
        requirement: '60 Días de Consistencia Épica',
        targetAmount: 60,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 60000,
          gold: 120000,
          essenceStones: 600,
          statPoints: 10,
          titleReward: 'Comandante del Raid de Jeju'
        }
      },
      {
        day: 90,
        title: 'Aniquilación del Rey Hormiga Beru (Día 90)',
        description: '90 días inquebrantables. Eres ahora una entidad de poder indiscutible.',
        requirement: '90 Días de Maestría Absoluta',
        targetAmount: 90,
        currentAmount: 1,
        unit: 'días',
        completed: false,
        claimed: false,
        reward: {
          xp: 150000,
          gold: 300000,
          essenceStones: 1500,
          statPoints: 20,
          titleReward: 'Soberano de la Isla Purificada'
        }
      }
    ],
    finalReward: {
      xp: 200000,
      gold: 500000,
      essenceStones: 2500,
      exclusiveTitle: 'Héroe de Rango Nacional',
      exclusiveItem: {
        id: 'item_beru_carapace',
        name: 'Coraza del Rey Hormiga Beru',
        description: 'Armadura forjada con el exoesqueleto de la calamidad de Jeju. Invulnerabilidad mental total.',
        rarity: 'Mythic',
        slot: 'chest',
        icon: 'shield_moon',
        priceGold: 150000,
        stats: { STR: 50, VIT: 50, AGI: 40, INT: 40, WIS: 40, CHA: 40 },
        effect: '+50% All Stats y Racha Protegida Permanente'
      }
    }
  }
];


