import React, { useState } from 'react';
import { Rank, QuestCategory, Quest, Player } from '../types';
import { HABIT_PRESETS, HabitPreset } from '../constants';
import { sound } from '../utils/sound';
import { DAILY_QUEST_CATALOG, CatalogQuest, getRandomDailyQuests, getRandomSingleQuest } from '../utils/dailyQuestCatalog';

interface QuestModalProps {
  player?: Player;
  onClose: () => void;
  onAdd: (quest: Omit<Quest, 'id' | 'completed' | 'createdAt'>) => void;
  defaultTab?: ModalTab;
}

type ModalTab = 'autonomous_ai' | 'custom_ai' | 'presets' | 'manual';

const QuestModal: React.FC<QuestModalProps> = ({ player, onClose, onAdd, defaultTab = 'autonomous_ai' }) => {
  const [activeTab, setActiveTab] = useState<ModalTab>(defaultTab);

  // Catalog & Random System State
  const [catalogSearch, setCatalogSearch] = useState('');
  const [catalogCategory, setCatalogCategory] = useState<string>('all');
  const [catalogRank, setCatalogRank] = useState<string>('all');
  const [addedNotice, setAddedNotice] = useState<string | null>(null);

  // Autonomous AI State
  const [autoCategory, setAutoCategory] = useState<string>('random');
  const [autoDifficulty, setAutoDifficulty] = useState<string>('Desafiante');
  const [isGeneratingAuto, setIsGeneratingAuto] = useState(false);
  const [autoGeneratedQuest, setAutoGeneratedQuest] = useState<any | null>(null);

  // Custom AI Generator State
  const [userGoal, setUserGoal] = useState('');
  const [attributeTarget, setAttributeTarget] = useState<'STR' | 'INT' | 'VIT' | 'AGI' | 'WIS' | 'CHA'>('STR');
  const [customDifficulty, setCustomDifficulty] = useState<'Normal' | 'Desafiante' | 'Rango S - Épico'>('Normal');
  const [isGeneratingCustom, setIsGeneratingCustom] = useState(false);
  const [customGeneratedQuest, setCustomGeneratedQuest] = useState<any | null>(null);

  // Manual Form State
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [rank, setRank] = useState<Rank>(Rank.E);
  const [category, setCategory] = useState<QuestCategory>('fitness');
  const [isDaily, setIsDaily] = useState<boolean>(true);
  const [targetCount, setTargetCount] = useState<number>(1);
  const [unit, setUnit] = useState<string>('reps');

  const [errorMsg, setErrorMsg] = useState('');

  // Compute recommended rewards based on Rank
  const getRewardsForRank = (r: Rank) => {
    switch (r) {
      case Rank.S: return { xp: 1200, gold: 1500, essenceStones: 25, statPoints: 2 };
      case Rank.A: return { xp: 600, gold: 750, essenceStones: 15, statPoints: 1 };
      case Rank.B: return { xp: 350, gold: 350, essenceStones: 8 };
      case Rank.C: return { xp: 220, gold: 180, essenceStones: 4 };
      case Rank.D: return { xp: 150, gold: 100, essenceStones: 2 };
      default: return { xp: 100, gold: 60, essenceStones: 1 };
    }
  };

  // 1. Autonomous AI Generation (System decides everything)
  const handleGenerateAutonomousQuest = async () => {
    setErrorMsg('');
    setIsGeneratingAuto(true);
    sound.playBeep(640, 0.08, 'sawtooth');

    try {
      const res = await fetch('/api/ai/generate-quest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          hunterName: player?.name || 'Sung Jin-Woo',
          rank: player?.rank || 'C-RANK',
          level: player?.level || 18,
          autonomous: true,
          attributeTarget: autoCategory === 'random' ? undefined : autoCategory,
          difficulty: autoDifficulty,
        }),
      });

      const data = await res.json();
      if (data.quest) {
        setAutoGeneratedQuest(data.quest);
        sound.playLevelUp();
        if (data.quest.systemMessage) {
          sound.speakSystemVoice(data.quest.systemMessage);
        }
      }
    } catch (err) {
      console.warn('Backend AI route unreachable, activating Client Oracle Fallback', err);
      // Client-side Solo Leveling Quest Generator
      const fallbackTitles = [
        '[Misión del Sistema: Purificación de Maná y Resistencia]',
        '[Misión Diaria: Templanza del Monarca de las Sombras]',
        '[Protocolo del Sistema: Ruptura de Inercia Mental]',
        '[Entrenamiento del Cazador: Foco Implacable]',
      ];
      const selectedTitle = fallbackTitles[Math.floor(Math.random() * fallbackTitles.length)];
      const fallbackQuest = {
        title: selectedTitle,
        description: 'El Sistema impone una prueba de templanza. Completa 30 minutos de trabajo profundo, lectura o ejercicio físico sin interrupciones.',
        targetCount: 30,
        unit: 'minutos',
        attributeReward: autoCategory === 'random' ? 'STR' : autoCategory,
        category: 'fitness',
        xpReward: 950,
        goldReward: 1600,
        essenceReward: 15,
        systemMessage: 'El estancamiento es la única muerte real. Cumple el protocolo.',
      };
      setAutoGeneratedQuest(fallbackQuest);
      sound.playLevelUp();
      sound.speakSystemVoice(fallbackQuest.systemMessage);
    } finally {
      setIsGeneratingAuto(false);
    }
  };

  // 2. Custom User-Goal AI Generation
  const handleGenerateCustomAIQuest = async () => {
    if (!userGoal.trim()) {
      setErrorMsg('Escribe tu objetivo o hábito de la vida real.');
      return;
    }

    setErrorMsg('');
    setIsGeneratingCustom(true);
    sound.playBeep(600, 0.08, 'sawtooth');

    try {
      const res = await fetch('/api/ai/generate-quest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          hunterName: player?.name || 'Sung Jin-Woo',
          rank: player?.rank || 'C-RANK',
          level: player?.level || 18,
          goalDescription: userGoal.trim(),
          attributeTarget,
          difficulty: customDifficulty,
        }),
      });

      const data = await res.json();
      if (data.quest) {
        setCustomGeneratedQuest(data.quest);
        sound.playLevelUp();
        if (data.quest.systemMessage) {
          sound.speakSystemVoice(data.quest.systemMessage);
        }
      }
    } catch (err) {
      console.warn('Backend AI route unreachable, activating Client Custom Quest Fallback', err);
      const customFallback = {
        title: `[Misión Diaria: ${userGoal.slice(0, 35)}]`,
        description: `El Sistema ha registrado tu directiva: "${userGoal}". Concluye el objetivo sin vacilar para fortalecer tu núcleo de maná.`,
        targetCount: 1,
        unit: 'completado',
        attributeReward: attributeTarget,
        category: 'habit',
        xpReward: 850,
        goldReward: 1400,
        essenceReward: 12,
        systemMessage: 'Tu voluntad define tu poder. Conquista esta prueba.',
      };
      setCustomGeneratedQuest(customFallback);
      sound.playLevelUp();
      sound.speakSystemVoice(customFallback.systemMessage);
    } finally {
      setIsGeneratingCustom(false);
    }
  };

  // Accept any AI quest
  const handleAcceptQuest = (q: any, diffStr: string, attr: string) => {
    if (!q) return;

    let targetRank = Rank.E;
    if (diffStr.includes('S') || diffStr.includes('Épico') || diffStr.includes('Calamidad')) targetRank = Rank.S;
    else if (diffStr.includes('A') || diffStr.includes('Desafiante')) targetRank = Rank.A;
    else if (diffStr.includes('B')) targetRank = Rank.B;
    else if (diffStr.includes('C')) targetRank = Rank.C;

    let questCat: QuestCategory = 'habit';
    if (attr === 'STR') questCat = 'fitness';
    else if (attr === 'INT') questCat = 'intellect';
    else if (attr === 'WIS') questCat = 'mindfulness';
    else if (attr === 'VIT') questCat = 'discipline';

    onAdd({
      title: q.title,
      description: q.description,
      rank: targetRank,
      category: questCat,
      isDaily: true,
      targetCount: Number(q.targetCount) || 1,
      currentCount: 0,
      unit: q.unit || 'veces',
      rewards: {
        xp: Number(q.xpReward) || 500,
        gold: Number(q.goldReward) || 1000,
        essenceStones: Number(q.essenceReward) || 10,
        statPoints: targetRank === Rank.S || targetRank === Rank.A ? 1 : 0,
      },
      aiGenerated: true,
      systemMessage: q.systemMessage,
    });
  };

  // 3. Adopt Catalog Quest
  const handleAdoptCatalogQuest = (item: CatalogQuest) => {
    sound.playLevelUp();
    const lvlMultiplier = 1 + Math.min(2, ((player?.level || 1) - 1) * 0.05);
    onAdd({
      title: item.title,
      description: item.description,
      rank: item.rank,
      category: item.category,
      isDaily: true,
      targetCount: item.targetCount,
      currentCount: 0,
      unit: item.unit,
      rewards: {
        xp: Math.round(item.xpReward * lvlMultiplier),
        gold: Math.round(item.goldReward * lvlMultiplier),
        essenceStones: item.essenceReward,
        statPoints: item.statPointsReward,
      },
    });
    setAddedNotice(`Misión "${item.title.slice(0, 30)}..." asignada al Sistema.`);
    setTimeout(() => setAddedNotice(null), 3500);
  };

  // Roll 1 Random Mission from Catalog
  const handleRollRandomQuest = () => {
    sound.playLevelUp();
    const randomQuest = getRandomSingleQuest(player?.level || 1);
    onAdd(randomQuest);
    setAddedNotice(`🎲 Misión aleatoria "${randomQuest.title.slice(0, 30)}..." agregada.`);
    setTimeout(() => setAddedNotice(null), 3500);
  };

  // Roll Balanced 4-Missions Daily Routine
  const handleRollBalancedRoutine = () => {
    sound.playAwakening();
    const routine = getRandomDailyQuests(4, player?.level || 1);
    routine.forEach((q) => onAdd(q));
    setAddedNotice(`⚡ ¡Rutina de 4 misiones diarias balanceadas asignadas!`);
    setTimeout(() => setAddedNotice(null), 4000);
  };

  // Legacy preset adopt fallback
  const handleAdoptPreset = (preset: HabitPreset) => {
    sound.playLevelUp();
    onAdd({
      title: preset.title,
      description: preset.description,
      rank: preset.rank,
      category: preset.category,
      isDaily: true,
      targetCount: preset.targetCount,
      currentCount: 0,
      unit: preset.unit,
      rewards: {
        xp: preset.xpReward,
        gold: preset.goldReward,
        essenceStones: preset.essenceReward,
      },
    });
  };

  // 4. Manual Submit
  const handleSubmitManual = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    sound.playLevelUp();
    onAdd({
      title: title.trim(),
      description: description.trim() || 'Misión registrada en el Sistema del Monarca.',
      rank,
      category,
      isDaily,
      targetCount: Number(targetCount) || 1,
      currentCount: 0,
      unit: unit.trim() || 'veces',
      rewards: getRewardsForRank(rank),
    });
  };

  const categories: { id: QuestCategory; label: string; icon: string }[] = [
    { id: 'fitness', label: 'Fuerza & Físico', icon: 'fitness_center' },
    { id: 'intellect', label: 'Estudio & Intelecto', icon: 'psychology' },
    { id: 'discipline', label: 'Disciplina & Trabajo', icon: 'verified' },
    { id: 'habit', label: 'Hábito Diario', icon: 'repeat' },
    { id: 'mindfulness', label: 'Mente & Salud', icon: 'self_improvement' },
  ];

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="absolute inset-0 bg-black/90 backdrop-blur-md" onClick={onClose}></div>

      <div className="relative w-full max-w-xl bg-[#090c14]/98 border-2 border-cyan-500/40 rounded-3xl shadow-[0_0_50px_rgba(6,182,212,0.2)] overflow-hidden my-4 sm:my-6 animate-modal gacha-panel">
        {/* Header */}
        <div className="bg-gradient-to-r from-cyan-950/60 via-blue-950/40 to-transparent p-4 sm:p-5 border-b border-cyan-500/20 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="material-symbols-outlined text-cyan-400 text-2xl animate-pulse">auto_awesome</span>
            <div>
              <h3 className="text-white text-base sm:text-lg font-black italic tracking-tighter uppercase font-display">
                Terminal de Misiones del Sistema
              </h3>
              <p className="text-slate-400 text-xs font-mono">
                IA Autónoma • Catálogo de Hábitos • Forja Personalizada
              </p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 transition-colors rounded-lg bg-white/5 active:scale-95"
          >
            <span className="material-symbols-outlined">close</span>
          </button>
        </div>

        {/* 4 Mode Selector Tabs */}
        <div className="px-3 pt-3 pb-2 grid grid-cols-4 gap-1.5 border-b border-cyan-500/15 bg-black/50">
          <button
            onClick={() => {
              sound.playBeep(520, 0.04);
              setActiveTab('autonomous_ai');
            }}
            className={`py-2 px-1 rounded-xl text-[10px] sm:text-[11px] font-black uppercase tracking-wider transition-all flex flex-col items-center justify-center gap-1 active:scale-95 touch-manipulation ${
              activeTab === 'autonomous_ai'
                ? 'bg-gradient-to-br from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/30'
                : 'bg-white/5 text-slate-400 hover:text-white'
            }`}
          >
            <span className="material-symbols-outlined text-base">smart_toy</span>
            <span>IA Autónoma</span>
          </button>

          <button
            onClick={() => {
              sound.playBeep(520, 0.04);
              setActiveTab('custom_ai');
            }}
            className={`py-2 px-1 rounded-xl text-[10px] sm:text-[11px] font-black uppercase tracking-wider transition-all flex flex-col items-center justify-center gap-1 active:scale-95 touch-manipulation ${
              activeTab === 'custom_ai'
                ? 'bg-gradient-to-br from-indigo-600 to-cyan-500 text-white shadow-lg shadow-indigo-600/30'
                : 'bg-white/5 text-slate-400 hover:text-white'
            }`}
          >
            <span className="material-symbols-outlined text-base">psychology</span>
            <span>Meta + IA</span>
          </button>

          <button
            onClick={() => {
              sound.playBeep(520, 0.04);
              setActiveTab('presets');
            }}
            className={`py-2 px-1 rounded-xl text-[10px] sm:text-[11px] font-black uppercase tracking-wider transition-all flex flex-col items-center justify-center gap-1 active:scale-95 touch-manipulation ${
              activeTab === 'presets'
                ? 'bg-gradient-to-br from-amber-500 to-yellow-500 text-black shadow-lg shadow-amber-500/30'
                : 'bg-white/5 text-slate-400 hover:text-white'
            }`}
          >
            <span className="material-symbols-outlined text-base">casino</span>
            <span>Catálogo</span>
          </button>

          <button
            onClick={() => {
              sound.playBeep(520, 0.04);
              setActiveTab('manual');
            }}
            className={`py-2 px-1 rounded-xl text-[10px] sm:text-[11px] font-black uppercase tracking-wider transition-all flex flex-col items-center justify-center gap-1 active:scale-95 touch-manipulation ${
              activeTab === 'manual'
                ? 'bg-gradient-to-br from-cyan-600 to-cyan-400 text-white shadow-lg shadow-cyan-600/30'
                : 'bg-white/5 text-slate-400 hover:text-white'
            }`}
          >
            <span className="material-symbols-outlined text-base">edit_note</span>
            <span>Manual</span>
          </button>
        </div>

        {/* Tab 1: 100% Autonomous AI */}
        {activeTab === 'autonomous_ai' && (
          <div className="p-6 space-y-5">
            {!autoGeneratedQuest ? (
              <div className="space-y-4">
                <div className="p-4 rounded-2xl bg-primary/10 border border-primary/30 text-xs text-slate-300 space-y-2">
                  <div className="flex items-center gap-2 text-primary font-black uppercase tracking-wider">
                    <span className="material-symbols-outlined text-base">auto_fix_high</span>
                    Modo Sistema Autónomo (NVIDIA Nemotron)
                  </div>
                  <p className="leading-relaxed">
                    No necesitas escribir nada. La Inteligencia Artificial del Sistema analizará tu Rango (<span className="text-primary font-bold">{player?.rank || 'C-RANK'}</span>) y Nivel (<span className="text-primary font-bold">{player?.level || 1}</span>) para forjar una misión imprevista de la vida real.
                  </p>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[10px] font-black uppercase text-slate-400 tracking-wider mb-1">
                      Enfoque de la Misión:
                    </label>
                    <select
                      value={autoCategory}
                      onChange={(e) => setAutoCategory(e.target.value)}
                      className="w-full bg-surface-card border border-white/10 rounded-xl p-2.5 text-xs text-white"
                    >
                      <option value="random">⚡ Sorpresa Total (Cualquier área)</option>
                      <option value="STR">Físico / Fuerza (STR)</option>
                      <option value="INT">Intelecto / Estudio (INT)</option>
                      <option value="VIT">Salud & Vitalidad (VIT)</option>
                      <option value="WIS">Mente & Sabiduría (WIS)</option>
                      <option value="AGI">Agilidad & Eficiencia (AGI)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-[10px] font-black uppercase text-slate-400 tracking-wider mb-1">
                      Intensidad de la Prueba:
                    </label>
                    <select
                      value={autoDifficulty}
                      onChange={(e) => setAutoDifficulty(e.target.value)}
                      className="w-full bg-surface-card border border-white/10 rounded-xl p-2.5 text-xs text-white"
                    >
                      <option value="Normal">Normal (Hábitos sostenibles)</option>
                      <option value="Desafiante">Desafiante (Subir de nivel)</option>
                      <option value="Rango S - Épico">Rango S - Límite Absoluto</option>
                    </select>
                  </div>
                </div>

                {errorMsg && <p className="text-red-400 text-xs font-bold">{errorMsg}</p>}

                <button
                  type="button"
                  onClick={handleGenerateAutonomousQuest}
                  disabled={isGeneratingAuto}
                  className={`w-full py-4 rounded-xl font-black uppercase text-xs tracking-wider flex items-center justify-center gap-2 transition-all shadow-xl ${
                    isGeneratingAuto
                      ? 'bg-primary/50 text-white cursor-wait animate-pulse'
                      : 'bg-gradient-to-r from-primary via-indigo-600 to-accent hover:opacity-95 text-white shadow-primary/30 active:scale-95'
                  }`}
                >
                  <span className="material-symbols-outlined text-base">
                    {isGeneratingAuto ? 'progress_activity' : 'bolt'}
                  </span>
                  {isGeneratingAuto ? 'El Sistema está invocando la misión...' : 'Dejar que el Sistema Invente mi Misión'}
                </button>
              </div>
            ) : (
              /* Preview of Autonomous AI Quest */
              <div className="space-y-4 animate-fadeIn">
                <div className="p-4 rounded-2xl bg-surface-card border-2 border-primary/60 space-y-3 system-glow">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded bg-primary/20 text-primary border border-primary/40 font-mono">
                      Misión Autónoma del Sistema
                    </span>
                    <span className="text-xs font-mono text-emerald-400 font-bold">
                      +{autoGeneratedQuest.xpReward} XP | +{autoGeneratedQuest.goldReward} G
                    </span>
                  </div>

                  <div>
                    <h4 className="text-white text-base font-black italic uppercase font-display">
                      {autoGeneratedQuest.title}
                    </h4>
                    <p className="text-slate-300 text-xs mt-1 leading-relaxed">
                      {autoGeneratedQuest.description}
                    </p>
                  </div>

                  <div className="p-2.5 bg-white/5 rounded-xl text-xs flex items-center justify-between font-mono">
                    <span className="text-slate-400">Meta Cuantificable:</span>
                    <span className="text-amber-400 font-bold">
                      {autoGeneratedQuest.targetCount} {autoGeneratedQuest.unit}
                    </span>
                  </div>

                  {autoGeneratedQuest.systemMessage && (
                    <div className="p-2 bg-indigo-950/40 border border-indigo-500/30 rounded-lg text-[11px] text-indigo-300 italic flex items-center gap-2">
                      <span className="material-symbols-outlined text-indigo-400 text-sm">terminal</span>
                      "{autoGeneratedQuest.systemMessage}"
                    </div>
                  )}
                </div>

                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => setAutoGeneratedQuest(null)}
                    className="flex-1 py-3 bg-white/5 hover:bg-white/10 text-slate-400 rounded-xl text-xs font-bold uppercase transition-all"
                  >
                    Otra Misión
                  </button>
                  <button
                    type="button"
                    onClick={() => handleAcceptQuest(autoGeneratedQuest, autoDifficulty, autoCategory)}
                    className="flex-2 py-3 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-black uppercase tracking-wider shadow-lg shadow-emerald-600/30 transition-all active:scale-95 flex items-center justify-center gap-1.5"
                  >
                    <span className="material-symbols-outlined text-sm">check_circle</span>
                    Aceptar Misión
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Tab 2: Custom User Goal AI Oracle */}
        {activeTab === 'custom_ai' && (
          <div className="p-6 space-y-5">
            {!customGeneratedQuest ? (
              <div className="space-y-4">
                <div>
                  <label className="block text-[11px] font-black uppercase text-slate-300 tracking-wider mb-1.5">
                    ¿Cuál es tu objetivo o hábito de hoy?
                  </label>
                  <textarea
                    value={userGoal}
                    onChange={(e) => setUserGoal(e.target.value)}
                    placeholder="Ej: Leer 20 páginas de finanzas, correr 5km, no comer comida chatarra, terminar reporte..."
                    rows={3}
                    className="w-full bg-surface-card border border-white/10 focus:border-primary focus:ring-1 focus:ring-primary rounded-xl p-3 text-sm text-white placeholder-slate-500 transition-all resize-none"
                  />
                  {errorMsg && <p className="text-red-400 text-xs mt-1 font-bold">{errorMsg}</p>}
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[10px] font-black uppercase text-slate-400 tracking-wider mb-1">
                      Atributo que Forja:
                    </label>
                    <select
                      value={attributeTarget}
                      onChange={(e) => setAttributeTarget(e.target.value as any)}
                      className="w-full bg-surface-card border border-white/10 rounded-xl p-2.5 text-xs text-white"
                    >
                      <option value="STR">Fuerza (STR) - Físico</option>
                      <option value="INT">Inteligencia (INT) - Estudio</option>
                      <option value="VIT">Vitalidad (VIT) - Salud / Agua</option>
                      <option value="AGI">Agilidad (AGI) - Rapidez</option>
                      <option value="WIS">Sabiduría (WIS) - Mente / Lectura</option>
                      <option value="CHA">Carisma (CHA) - Social</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-[10px] font-black uppercase text-slate-400 tracking-wider mb-1">
                      Dificultad:
                    </label>
                    <select
                      value={customDifficulty}
                      onChange={(e) => setCustomDifficulty(e.target.value as any)}
                      className="w-full bg-surface-card border border-white/10 rounded-xl p-2.5 text-xs text-white"
                    >
                      <option value="Normal">Normal (Rango C)</option>
                      <option value="Desafiante">Desafiante (Rango B-A)</option>
                      <option value="Rango S - Épico">Calamidad (Rango S)</option>
                    </select>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleGenerateCustomAIQuest}
                  disabled={isGeneratingCustom || !userGoal.trim()}
                  className={`w-full py-3.5 rounded-xl font-black uppercase text-xs tracking-wider flex items-center justify-center gap-2 transition-all shadow-lg ${
                    isGeneratingCustom
                      ? 'bg-primary/50 text-white cursor-wait animate-pulse'
                      : userGoal.trim()
                      ? 'bg-gradient-to-r from-primary via-indigo-600 to-accent hover:from-primary hover:to-primary text-white shadow-primary/30 active:scale-95'
                      : 'bg-white/5 border border-white/10 text-slate-500 cursor-not-allowed'
                  }`}
                >
                  <span className="material-symbols-outlined text-base">
                    {isGeneratingCustom ? 'progress_activity' : 'psychology'}
                  </span>
                  {isGeneratingCustom ? 'Gamificando tu objetivo...' : 'Transformar en Misión con IA'}
                </button>
              </div>
            ) : (
              /* Preview of Custom AI Quest */
              <div className="space-y-4 animate-fadeIn">
                <div className="p-4 rounded-2xl bg-surface-card border-2 border-primary/60 space-y-3 system-glow">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded bg-primary/20 text-primary border border-primary/40 font-mono">
                      Misión Personalizada
                    </span>
                    <span className="text-xs font-mono text-emerald-400 font-bold">
                      +{customGeneratedQuest.xpReward} XP | +{customGeneratedQuest.goldReward} G
                    </span>
                  </div>

                  <div>
                    <h4 className="text-white text-base font-black italic uppercase font-display">
                      {customGeneratedQuest.title}
                    </h4>
                    <p className="text-slate-300 text-xs mt-1 leading-relaxed">
                      {customGeneratedQuest.description}
                    </p>
                  </div>

                  <div className="p-2.5 bg-white/5 rounded-xl text-xs flex items-center justify-between font-mono">
                    <span className="text-slate-400">Meta Cuantificable:</span>
                    <span className="text-amber-400 font-bold">
                      {customGeneratedQuest.targetCount} {customGeneratedQuest.unit}
                    </span>
                  </div>

                  {customGeneratedQuest.systemMessage && (
                    <div className="p-2 bg-indigo-950/40 border border-indigo-500/30 rounded-lg text-[11px] text-indigo-300 italic flex items-center gap-2">
                      <span className="material-symbols-outlined text-indigo-400 text-sm">terminal</span>
                      "{customGeneratedQuest.systemMessage}"
                    </div>
                  )}
                </div>

                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => setCustomGeneratedQuest(null)}
                    className="flex-1 py-3 bg-white/5 hover:bg-white/10 text-slate-400 rounded-xl text-xs font-bold uppercase transition-all"
                  >
                    Regenerar
                  </button>
                  <button
                    type="button"
                    onClick={() => handleAcceptQuest(customGeneratedQuest, customDifficulty, attributeTarget)}
                    className="flex-2 py-3 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-black uppercase tracking-wider shadow-lg shadow-emerald-600/30 transition-all active:scale-95 flex items-center justify-center gap-1.5"
                  >
                    <span className="material-symbols-outlined text-sm">check_circle</span>
                    Aceptar Misión
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Tab 3: Preset Habits & Varied Catalog */}
        {activeTab === 'presets' && (
          <div className="p-4 sm:p-6 space-y-4 max-h-[65vh] overflow-y-auto">
            {/* Quick Random Generators Header */}
            <div className="p-3.5 bg-gradient-to-r from-amber-950/40 via-surface-card to-amber-950/20 border border-amber-500/30 rounded-2xl space-y-2.5">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-amber-400 text-lg">casino</span>
                  <span className="text-white text-xs font-black uppercase tracking-wider font-display">
                    Generador Aleatorio de Misiones
                  </span>
                </div>
                <span className="text-[10px] font-mono text-amber-400 font-bold bg-amber-400/10 px-2 py-0.5 rounded border border-amber-400/20">
                  {DAILY_QUEST_CATALOG.length} Misiones en Catálogo
                </span>
              </div>

              <p className="text-slate-400 text-[11px] leading-relaxed">
                Elige misiones pre-forjadas organizadas por estadísticas (Fuerza, Intelecto, Hábitos, Temple) o tira dados para asignar objetivos aleatorios inmediatos.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                <button
                  type="button"
                  onClick={handleRollRandomQuest}
                  className="py-2.5 px-3 bg-gradient-to-r from-amber-600 to-amber-500 hover:from-amber-500 hover:to-amber-400 text-black font-black text-xs uppercase tracking-wider rounded-xl flex items-center justify-center gap-2 shadow-md shadow-amber-600/30 active:scale-95 transition-all"
                >
                  <span className="material-symbols-outlined text-base">casino</span>
                  <span>1 Misión Aleatoria (1 Clic)</span>
                </button>

                <button
                  type="button"
                  onClick={handleRollBalancedRoutine}
                  className="py-2.5 px-3 bg-gradient-to-r from-primary to-indigo-600 hover:from-primary hover:to-primary text-white font-black text-xs uppercase tracking-wider rounded-xl flex items-center justify-center gap-2 shadow-md shadow-primary/30 active:scale-95 transition-all"
                >
                  <span className="material-symbols-outlined text-base">bolt</span>
                  <span>Rutina Diaria (4 Variadas)</span>
                </button>
              </div>

              {addedNotice && (
                <div className="p-2 bg-emerald-950/60 border border-emerald-500/40 rounded-xl text-emerald-300 text-xs font-mono font-bold flex items-center gap-2 animate-fadeIn">
                  <span className="material-symbols-outlined text-emerald-400 text-sm">check_circle</span>
                  <span>{addedNotice}</span>
                </div>
              )}
            </div>

            {/* Search & Category Filter Bar */}
            <div className="space-y-2">
              <div className="flex gap-2">
                <div className="relative flex-1">
                  <input
                    type="text"
                    value={catalogSearch}
                    onChange={(e) => setCatalogSearch(e.target.value)}
                    placeholder="Buscar misión en el catálogo..."
                    className="w-full bg-surface-dark border border-white/10 rounded-xl pl-9 pr-3 py-2 text-xs text-white placeholder:text-slate-500 focus:border-amber-400 focus:outline-none"
                  />
                  <span className="material-symbols-outlined text-slate-500 text-base absolute left-2.5 top-2.5">
                    search
                  </span>
                </div>

                <select
                  value={catalogRank}
                  onChange={(e) => setCatalogRank(e.target.value)}
                  className="bg-surface-dark border border-white/10 rounded-xl px-2.5 py-2 text-xs text-slate-300 font-mono focus:border-amber-400 focus:outline-none"
                >
                  <option value="all">Rango: Todos</option>
                  <option value={Rank.S}>Rango S</option>
                  <option value={Rank.A}>Rango A</option>
                  <option value={Rank.B}>Rango B</option>
                  <option value={Rank.C}>Rango C</option>
                  <option value={Rank.D}>Rango D</option>
                  <option value={Rank.E}>Rango E</option>
                </select>
              </div>

              {/* Category chips */}
              <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none text-[11px]">
                {[
                  { id: 'all', label: 'Todas' },
                  { id: 'STR', label: 'Fuerza (STR)' },
                  { id: 'INT', label: 'Intelecto (INT)' },
                  { id: 'VIT', label: 'Vitalidad (VIT)' },
                  { id: 'AGI', label: 'Agilidad (AGI)' },
                  { id: 'WIS', label: 'Sabiduría (WIS)' },
                  { id: 'CHA', label: 'Carisma (CHA)' },
                ].map((chip) => (
                  <button
                    key={chip.id}
                    type="button"
                    onClick={() => {
                      sound.playBeep(650, 0.02);
                      setCatalogCategory(chip.id);
                    }}
                    className={`px-2.5 py-1 rounded-lg font-bold whitespace-nowrap transition-all ${
                      catalogCategory === chip.id
                        ? 'bg-amber-500 text-black shadow-sm'
                        : 'bg-white/5 text-slate-400 hover:text-white hover:bg-white/10'
                    }`}
                  >
                    {chip.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Catalog List */}
            <div className="space-y-3">
              {DAILY_QUEST_CATALOG.filter((item) => {
                if (catalogCategory !== 'all' && item.attributeTarget !== catalogCategory) return false;
                if (catalogRank !== 'all' && item.rank !== catalogRank) return false;
                if (catalogSearch.trim()) {
                  const q = catalogSearch.toLowerCase();
                  return (
                    item.title.toLowerCase().includes(q) ||
                    item.description.toLowerCase().includes(q) ||
                    item.attributeTarget.toLowerCase().includes(q)
                  );
                }
                return true;
              }).map((item) => (
                <div
                  key={item.id}
                  className="p-4 bg-[#101422] border border-cyan-500/20 hover:border-amber-500/50 rounded-2xl transition-all space-y-3 group shadow-md shadow-black/40"
                >
                  {/* Top Row: Icon, Ranks, Title & Action Button */}
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-3 flex-1 min-w-0">
                      <div className="size-10 rounded-xl bg-amber-500/15 border border-amber-500/30 flex items-center justify-center text-amber-400 shrink-0 mt-0.5 shadow-sm shadow-amber-500/10">
                        <span className="material-symbols-outlined text-xl">{item.icon}</span>
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex flex-wrap items-center gap-1.5 mb-1">
                          <span className={`text-[9px] font-black uppercase px-2 py-0.5 rounded border font-mono ${
                            item.rank === Rank.S ? 'bg-amber-500/20 text-amber-300 border-amber-500/40' :
                            item.rank === Rank.A ? 'bg-purple-500/20 text-purple-300 border-purple-500/40' :
                            item.rank === Rank.B ? 'bg-blue-500/20 text-blue-300 border-blue-500/40' :
                            'bg-slate-800 text-slate-300 border-white/10'
                          }`}>
                            {item.rank}
                          </span>
                          <span className="text-[10px] font-mono font-bold text-cyan-400 bg-cyan-950/50 px-1.5 py-0.5 rounded border border-cyan-500/30">
                            +{item.attributeTarget}
                          </span>
                        </div>
                        <h4 className="text-white text-sm font-bold font-display group-hover:text-amber-300 transition-colors leading-snug break-words">
                          {item.title}
                        </h4>
                      </div>
                    </div>

                    <button
                      type="button"
                      onClick={() => handleAdoptCatalogQuest(item)}
                      className="btn-gacha btn-gacha-gold px-3.5 py-2 text-xs rounded-xl shrink-0 active:scale-95 touch-manipulation"
                      title="Asignar esta misión a tus misiones activas"
                    >
                      + Asignar
                    </button>
                  </div>

                  {/* Full, completely visible description without any line-clamp */}
                  <div className="bg-[#080b12] border border-white/5 rounded-xl p-2.5">
                    <p className="text-slate-200 text-xs leading-relaxed break-words font-normal">
                      {item.description}
                    </p>
                  </div>

                  {/* Rewards & Target Metrics Bar */}
                  <div className="flex flex-wrap items-center justify-between gap-2 pt-0.5 text-[10.5px] font-mono">
                    <div className="flex items-center gap-1.5 bg-amber-400/10 text-amber-300 font-bold px-2 py-1 rounded-lg border border-amber-400/25">
                      <span className="material-symbols-outlined text-xs">flag</span>
                      <span>Meta: {item.targetCount} {item.unit}</span>
                    </div>

                    <div className="flex items-center gap-2.5 text-slate-300 font-semibold">
                      <span className="text-emerald-400 font-bold">+{item.xpReward} XP</span>
                      <span className="text-amber-400 font-bold">+{item.goldReward} G</span>
                      {item.essenceReward > 0 && (
                        <span className="text-cyan-400 font-bold">+{item.essenceReward} Gemas</span>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Tab 4: Manual Creation */}
        {activeTab === 'manual' && (
          <form onSubmit={handleSubmitManual} className="p-6 space-y-4">
            <div>
              <label className="block text-[11px] font-black uppercase text-slate-300 tracking-wider mb-1.5">
                Título de la Misión *
              </label>
              <input
                type="text"
                required
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="ej. Correr 5km, Leer 30 minutos..."
                className="w-full bg-surface-card border border-white/10 focus:border-primary focus:ring-1 focus:ring-primary rounded-xl p-3 text-sm text-white placeholder-slate-500 transition-all"
              />
            </div>

            <div>
              <label className="block text-[11px] font-black uppercase text-slate-300 tracking-wider mb-1.5">
                Descripción / Instrucciones
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Detalles sobre cómo completar la prueba con éxito..."
                rows={2}
                className="w-full bg-surface-card border border-white/10 focus:border-primary focus:ring-1 focus:ring-primary rounded-xl p-3 text-xs text-white placeholder-slate-500 transition-all resize-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] font-black uppercase text-slate-300 tracking-wider mb-1.5">
                  Rango de Dificultad
                </label>
                <select
                  value={rank}
                  onChange={(e) => setRank(e.target.value as Rank)}
                  className="w-full bg-surface-card border border-white/10 rounded-xl p-3 text-xs text-white font-mono"
                >
                  <option value={Rank.E}>Rango E (Básico)</option>
                  <option value={Rank.D}>Rango D (Fácil)</option>
                  <option value={Rank.C}>Rango C (Moderado)</option>
                  <option value={Rank.B}>Rango B (Avanzado)</option>
                  <option value={Rank.A}>Rango A (Élite)</option>
                  <option value={Rank.S}>Rango S (Monarca)</option>
                </select>
              </div>

              <div>
                <label className="block text-[11px] font-black uppercase text-slate-300 tracking-wider mb-1.5">
                  Categoría
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value as QuestCategory)}
                  className="w-full bg-surface-card border border-white/10 rounded-xl p-3 text-xs text-white"
                >
                  {categories.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.label}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] font-black uppercase text-slate-300 tracking-wider mb-1.5">
                  Cantidad Objetivo
                </label>
                <input
                  type="number"
                  min="1"
                  value={targetCount}
                  onChange={(e) => setTargetCount(Math.max(1, parseInt(e.target.value) || 1))}
                  className="w-full bg-surface-card border border-white/10 rounded-xl p-3 text-xs text-white font-mono"
                />
              </div>

              <div>
                <label className="block text-[11px] font-black uppercase text-slate-300 tracking-wider mb-1.5">
                  Unidad de Medida
                </label>
                <input
                  type="text"
                  value={unit}
                  onChange={(e) => setUnit(e.target.value)}
                  placeholder="ej. reps, mins, km..."
                  className="w-full bg-surface-card border border-white/10 rounded-xl p-3 text-xs text-white font-mono"
                />
              </div>
            </div>

            {/* Footer Buttons */}
            <div className="pt-2 flex items-center justify-end gap-3 border-t border-white/5">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2.5 text-slate-400 hover:text-white text-xs font-bold uppercase transition-colors"
              >
                Cancelar
              </button>
              <button
                type="submit"
                className="px-6 py-2.5 bg-primary hover:bg-accent text-white text-xs font-black uppercase tracking-wider rounded-xl transition-all shadow-lg shadow-primary/30 active:scale-95"
              >
                Inscribir Misión
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};

export default QuestModal;

