import { Quest, QuestCategory, Rank } from '../types';

export interface CatalogQuest {
  id: string;
  title: string;
  description: string;
  category: QuestCategory;
  rank: Rank;
  targetCount: number;
  unit: string;
  attributeTarget: 'STR' | 'INT' | 'VIT' | 'AGI' | 'WIS' | 'CHA';
  icon: string;
  xpReward: number;
  goldReward: number;
  essenceReward: number;
  statPointsReward?: number;
}

export const DAILY_QUEST_CATALOG: CatalogQuest[] = [
  // ==========================================
  // FUERZA & COMBATE FÍSICO (STR / Fitness)
  // ==========================================
  {
    id: 'cat_str_1',
    title: 'Entrenamiento Jin-Woo: 100 Flexiones & 100 Sentadillas',
    description: 'Rutina fundamental de acondicionamiento de combate para forjar resistencia de acero.',
    category: 'fitness',
    rank: Rank.B,
    targetCount: 200,
    unit: 'reps',
    attributeTarget: 'STR',
    icon: 'fitness_center',
    xpReward: 420,
    goldReward: 350,
    essenceReward: 12,
  },
  {
    id: 'cat_str_2',
    title: 'Marcha de la Cuerda & Cardio HIIT: 20 Minutos',
    description: 'Intervalos de alta intensidad para maximizar capacidad pulmonar y respuesta muscular.',
    category: 'fitness',
    rank: Rank.C,
    targetCount: 20,
    unit: 'minutos',
    attributeTarget: 'STR',
    icon: 'bolt',
    xpReward: 260,
    goldReward: 200,
    essenceReward: 8,
  },
  {
    id: 'cat_str_3',
    title: 'Dominadas de la Sombra: 25 Repeticiones',
    description: 'Elevar el peso corporal contra la gravedad para expandir la espalda y dorsales.',
    category: 'fitness',
    rank: Rank.A,
    targetCount: 25,
    unit: 'reps',
    attributeTarget: 'STR',
    icon: 'sports_gymnastics',
    xpReward: 550,
    goldReward: 450,
    essenceReward: 16,
    statPointsReward: 1,
  },
  {
    id: 'cat_str_4',
    title: 'Plancha Abdominal Inquebrantable: 3 Minutos Acumulados',
    description: 'Fortalecer el núcleo y la cintura para resistir el impacto cinético de los enemigos.',
    category: 'fitness',
    rank: Rank.D,
    targetCount: 3,
    unit: 'minutos',
    attributeTarget: 'STR',
    icon: 'shield',
    xpReward: 190,
    goldReward: 130,
    essenceReward: 5,
  },
  {
    id: 'cat_str_5',
    title: 'Fondos de Tríceps en Paralelas: 40 Repeticiones',
    description: 'Empuje vertical estricto para desarrollar potencia de bloqueo en brazos.',
    category: 'fitness',
    rank: Rank.C,
    targetCount: 40,
    unit: 'reps',
    attributeTarget: 'STR',
    icon: 'sports_mma',
    xpReward: 240,
    goldReward: 180,
    essenceReward: 7,
  },
  {
    id: 'cat_str_6',
    title: 'Ascenso a la Cumbre: 5 Kilómetros de Carrera Continua',
    description: 'Prueba de resistencia cardiorrespiratoria manteniendo ritmo constante de trote.',
    category: 'fitness',
    rank: Rank.B,
    targetCount: 5,
    unit: 'km',
    attributeTarget: 'STR',
    icon: 'directions_run',
    xpReward: 450,
    goldReward: 380,
    essenceReward: 14,
  },
  {
    id: 'cat_str_7',
    title: 'Burpees Explosivos: 50 Repeticiones',
    description: 'Combina flexión de pecho y salto vertical para activar el 100% de la masa corporal.',
    category: 'fitness',
    rank: Rank.B,
    targetCount: 50,
    unit: 'reps',
    attributeTarget: 'STR',
    icon: 'local_fire_department',
    xpReward: 380,
    goldReward: 300,
    essenceReward: 10,
  },
  {
    id: 'cat_str_8',
    title: 'Zancadas Dinámicas del Monarca: 80 Pasos',
    description: 'Caminar flexionando rodillas a 90 grados para blindar cuadríceps y glúteos.',
    category: 'fitness',
    rank: Rank.D,
    targetCount: 80,
    unit: 'pasos',
    attributeTarget: 'STR',
    icon: 'steps',
    xpReward: 180,
    goldReward: 130,
    essenceReward: 5,
  },
  {
    id: 'cat_str_9',
    title: 'Caminar con Peso del Destino: 15m Farmer Carry',
    description: 'Caminar transportando mancuernas o mochilas pesadas para fortalecer agarre y trapecios.',
    category: 'fitness',
    rank: Rank.C,
    targetCount: 15,
    unit: 'minutos',
    attributeTarget: 'STR',
    icon: 'handyman',
    xpReward: 280,
    goldReward: 210,
    essenceReward: 8,
  },

  // ==========================================
  // INTELIGENCIA & CONQUISTA COGNITIVA (INT / Intellect)
  // ==========================================
  {
    id: 'cat_int_1',
    title: 'Inmersión Técnica: 45 Minutos de Lectura Especializada',
    description: 'Absorber libros de arquitectura, ciencia, ingeniería o desarrollo sin distraerse.',
    category: 'intellect',
    rank: Rank.B,
    targetCount: 45,
    unit: 'minutos',
    attributeTarget: 'INT',
    icon: 'menu_book',
    xpReward: 380,
    goldReward: 300,
    essenceReward: 12,
  },
  {
    id: 'cat_int_2',
    title: 'Arquitectura de Código: Resolver 1 Desafío Algorítmico',
    description: 'Optimizar estructuras de datos y complejidad temporal en un reto de lógica pura.',
    category: 'intellect',
    rank: Rank.A,
    targetCount: 1,
    unit: 'problema',
    attributeTarget: 'INT',
    icon: 'terminal',
    xpReward: 520,
    goldReward: 420,
    essenceReward: 15,
    statPointsReward: 1,
  },
  {
    id: 'cat_int_3',
    title: 'Inmersión Lingüística: 25 Minutos de Idioma Extranjero',
    description: 'Estudiar gramática, vocabulario y práctica auditiva en una lengua de otro reino.',
    category: 'intellect',
    rank: Rank.D,
    targetCount: 25,
    unit: 'minutos',
    attributeTarget: 'INT',
    icon: 'translate',
    xpReward: 190,
    goldReward: 140,
    essenceReward: 5,
  },
  {
    id: 'cat_int_4',
    title: 'Resumen Estratégico: Redactar 500 Palabras Claras',
    description: 'Sintetizar conceptos complejos en un documento técnico de alta densidad informativa.',
    category: 'intellect',
    rank: Rank.C,
    targetCount: 500,
    unit: 'palabras',
    attributeTarget: 'INT',
    icon: 'edit_note',
    xpReward: 270,
    goldReward: 200,
    essenceReward: 8,
  },
  {
    id: 'cat_int_5',
    title: 'Análisis de Sistemas: Auditar y Refactorizar un Módulo',
    description: 'Revisar código o procesos obsoletos para eliminar deuda técnica y cuellos de botella.',
    category: 'intellect',
    rank: Rank.B,
    targetCount: 1,
    unit: 'módulo',
    attributeTarget: 'INT',
    icon: 'account_tree',
    xpReward: 410,
    goldReward: 320,
    essenceReward: 11,
  },
  {
    id: 'cat_int_6',
    title: 'Micro-Aprendizaje Prohibido: Ver 1 Masterclass Técnica',
    description: 'Estudiar una ponencia o tutorial de alto nivel tomando apuntes accionables.',
    category: 'intellect',
    rank: Rank.E,
    targetCount: 1,
    unit: 'clase',
    attributeTarget: 'INT',
    icon: 'school',
    xpReward: 150,
    goldReward: 100,
    essenceReward: 4,
  },
  {
    id: 'cat_int_7',
    title: 'Maestría en Herramientas: Aprender 5 Atajos Nuevos',
    description: 'Memorizar comandos y shortcuts de teclado para acelerar la velocidad de desarrollo.',
    category: 'intellect',
    rank: Rank.E,
    targetCount: 5,
    unit: 'atajos',
    attributeTarget: 'INT',
    icon: 'keyboard',
    xpReward: 140,
    goldReward: 90,
    essenceReward: 3,
  },
  {
    id: 'cat_int_8',
    title: 'Resolución de Rompecabezas Lógico o Ajedrez: 3 Partidas',
    description: 'Entrenar el cálculo de variantes y anticipación de movimientos rivales.',
    category: 'intellect',
    rank: Rank.D,
    targetCount: 3,
    unit: 'partidas',
    attributeTarget: 'INT',
    icon: 'extension',
    xpReward: 200,
    goldReward: 150,
    essenceReward: 6,
  },

  // ==========================================
  // VITALIDAD & TEMPLANZA BIOLÓGICA (VIT / Health & Recovery)
  // ==========================================
  {
    id: 'cat_vit_1',
    title: 'Elixir de Maná Puro: 3.0 Litros de Agua',
    description: 'Mantener hidratación celular perfecta para depurar toxinas y acelerar la recuperación.',
    category: 'habit',
    rank: Rank.E,
    targetCount: 3000,
    unit: 'ml',
    attributeTarget: 'VIT',
    icon: 'water_drop',
    xpReward: 160,
    goldReward: 110,
    essenceReward: 4,
  },
  {
    id: 'cat_vit_2',
    title: 'Inmersión Glacial: Ducha Helada de 3 Minutos',
    description: 'Activar el nervio vago y la respuesta de shock térmico para resetear la fatiga mental.',
    category: 'discipline',
    rank: Rank.C,
    targetCount: 3,
    unit: 'minutos',
    attributeTarget: 'VIT',
    icon: 'ac_unit',
    xpReward: 280,
    goldReward: 210,
    essenceReward: 8,
  },
  {
    id: 'cat_vit_3',
    title: 'Purga de Veneno: Cero Azúcares Añadidos ni Ultraprocesados',
    description: 'Nutrir al cazador exclusivamente con alimentos enteros, proteínas limpias y verduras.',
    category: 'habit',
    rank: Rank.B,
    targetCount: 1,
    unit: 'día limpio',
    attributeTarget: 'VIT',
    icon: 'restaurant',
    xpReward: 360,
    goldReward: 280,
    essenceReward: 12,
  },
  {
    id: 'cat_vit_4',
    title: 'Sueño del Monarca: 8 Horas en Oscuridad Absoluta',
    description: 'Descanso profundo para permitir que el Sistema repare los tejidos dañados y el maná.',
    category: 'habit',
    rank: Rank.C,
    targetCount: 8,
    unit: 'horas',
    attributeTarget: 'VIT',
    icon: 'bedtime',
    xpReward: 260,
    goldReward: 190,
    essenceReward: 7,
  },
  {
    id: 'cat_vit_5',
    title: 'Sincronización Circadiana: 15 Minutos de Sol Matutino',
    description: 'Recibir luz solar matutina en los ojos y piel para regular melatonina y cortisol.',
    category: 'habit',
    rank: Rank.E,
    targetCount: 15,
    unit: 'minutos',
    attributeTarget: 'VIT',
    icon: 'wb_sunny',
    xpReward: 150,
    goldReward: 100,
    essenceReward: 4,
  },
  {
    id: 'cat_vit_6',
    title: 'Pausa Anti-Sedentarismo: Caminar 5 Minutos cada Hora',
    description: 'Evitar rigidez en la columna vertebral y mantener la circulación sanguínea activa.',
    category: 'habit',
    rank: Rank.D,
    targetCount: 6,
    unit: 'pausas',
    attributeTarget: 'VIT',
    icon: 'accessibility_new',
    xpReward: 190,
    goldReward: 130,
    essenceReward: 5,
  },
  {
    id: 'cat_vit_7',
    title: 'Recarga de Electrolitos y Suplementos Esenciales',
    description: 'Magnesio, potasio y vitaminas del complejo B para soportar el desgaste físico.',
    category: 'habit',
    rank: Rank.E,
    targetCount: 1,
    unit: 'toma',
    attributeTarget: 'VIT',
    icon: 'medication',
    xpReward: 130,
    goldReward: 80,
    essenceReward: 3,
  },

  // ==========================================
  // AGILIDAD & HÁBITOS DIARIOS (AGI / Agility & Execution)
  // ==========================================
  {
    id: 'cat_agi_1',
    title: 'Marcha Incansable: 10,000 Pasos Diarios',
    description: 'Desplazamiento constante para mantener el metabolismo elevado y quemar ácido láctico.',
    category: 'fitness',
    rank: Rank.C,
    targetCount: 10000,
    unit: 'pasos',
    attributeTarget: 'AGI',
    icon: 'directions_walk',
    xpReward: 290,
    goldReward: 220,
    essenceReward: 9,
  },
  {
    id: 'cat_agi_2',
    title: 'Regla de los Dos Minutos: 5 Micro-Tareas Inmediatas',
    description: 'Cualquier tarea que tome menos de 120 segundos se ejecuta en el instante sin postergar.',
    category: 'discipline',
    rank: Rank.D,
    targetCount: 5,
    unit: 'tareas',
    attributeTarget: 'AGI',
    icon: 'speed',
    xpReward: 200,
    goldReward: 140,
    essenceReward: 6,
  },
  {
    id: 'cat_agi_3',
    title: 'Santuario Despejado: Orden y Limpieza en 15 Minutos',
    description: 'Limpiar el escritorio de trabajo y habitación para optimizar la velocidad mental.',
    category: 'habit',
    rank: Rank.E,
    targetCount: 15,
    unit: 'minutos',
    attributeTarget: 'AGI',
    icon: 'cleaning_services',
    xpReward: 150,
    goldReward: 100,
    essenceReward: 4,
  },
  {
    id: 'cat_agi_4',
    title: 'Desconexión Crepuscular: Dejar Pantallas 45m Antes de Dormir',
    description: 'Proteger la vista de luz azul para inducir una fase REM inmediata al acostarse.',
    category: 'habit',
    rank: Rank.C,
    targetCount: 45,
    unit: 'minutos',
    attributeTarget: 'AGI',
    icon: 'phonelink_off',
    xpReward: 240,
    goldReward: 180,
    essenceReward: 7,
  },
  {
    id: 'cat_agi_5',
    title: 'Bloques Pomodoro: 4 Ciclos de Ejecución Rápida (25m + 5m)',
    description: 'Sprint de enfoque táctico alternado con descansos cronometrados.',
    category: 'discipline',
    rank: Rank.B,
    targetCount: 4,
    unit: 'pomodoros',
    attributeTarget: 'AGI',
    icon: 'timer',
    xpReward: 340,
    goldReward: 260,
    essenceReward: 10,
  },
  {
    id: 'cat_agi_6',
    title: 'Bandeja de Entrada a Cero: Procesar Correos y Mensajes',
    description: 'Eliminar ruido y responder con brevedad para liberar carga cognitiva acumulada.',
    category: 'discipline',
    rank: Rank.D,
    targetCount: 1,
    unit: 'inbox',
    attributeTarget: 'AGI',
    icon: 'mark_email_read',
    xpReward: 180,
    goldReward: 130,
    essenceReward: 5,
  },

  // ==========================================
  // SABIDURÍA & TEMPLE MENTAL (WIS / Mindfulness & Mental Armor)
  // ==========================================
  {
    id: 'cat_wis_1',
    title: 'Meditación del Vacío: 20 Minutos de Silencio Absoluto',
    description: 'Observar pensamientos sin juzgarlos para templar el control emocional del Monarca.',
    category: 'mindfulness',
    rank: Rank.C,
    targetCount: 20,
    unit: 'minutos',
    attributeTarget: 'WIS',
    icon: 'self_improvement',
    xpReward: 270,
    goldReward: 200,
    essenceReward: 8,
  },
  {
    id: 'cat_wis_2',
    title: 'Diario Estoico: 3 Agradecimientos & 3 Lecciones de Batalla',
    description: 'Escribir reflexiones sinceras sobre aciertos, derrotas y visión estratégica.',
    category: 'mindfulness',
    rank: Rank.D,
    targetCount: 1,
    unit: 'entrada',
    attributeTarget: 'WIS',
    icon: 'auto_stories',
    xpReward: 190,
    goldReward: 130,
    essenceReward: 5,
  },
  {
    id: 'cat_wis_3',
    title: 'Ayuno de Dopamina: 2 Horas Continuas Sin Redes Sociales',
    description: 'Bloquear feeds algorítmicos y scrolls infinitos para regenerar receptores de dopamina.',
    category: 'discipline',
    rank: Rank.B,
    targetCount: 120,
    unit: 'minutos',
    attributeTarget: 'WIS',
    icon: 'do_not_disturb_on',
    xpReward: 410,
    goldReward: 310,
    essenceReward: 13,
  },
  {
    id: 'cat_wis_4',
    title: 'Técnica Box Breathing: 4 Rondas (Inhalar 4s - Retener 4s - Exhalar 4s - Pausa 4s)',
    description: 'Protocolo de respiración militar para reducir ritmo cardíaco ante el caos.',
    category: 'mindfulness',
    rank: Rank.E,
    targetCount: 4,
    unit: 'rondas',
    attributeTarget: 'WIS',
    icon: 'air',
    xpReward: 140,
    goldReward: 90,
    essenceReward: 3,
  },
  {
    id: 'cat_wis_5',
    title: 'Caminar en Silencio Puro: 20 Minutos Sin Teléfono ni Auriculares',
    description: 'Reconectar con el entorno y escuchar los pensamientos profundos sin estímulos externos.',
    category: 'mindfulness',
    rank: Rank.D,
    targetCount: 20,
    unit: 'minutos',
    attributeTarget: 'WIS',
    icon: 'nature_people',
    xpReward: 210,
    goldReward: 150,
    essenceReward: 6,
  },
  {
    id: 'cat_wis_6',
    title: 'Lectura Filosófica Estoica: 15 Minutos de Sabiduría Antigua',
    description: 'Estudiar principios de Marco Aurelio, Epicteto o filosofía Zen aplicada a la acción.',
    category: 'mindfulness',
    rank: Rank.C,
    targetCount: 15,
    unit: 'minutos',
    attributeTarget: 'WIS',
    icon: 'menu_book',
    xpReward: 230,
    goldReward: 170,
    essenceReward: 7,
  },

  // ==========================================
  // CARISMA & PRESENCIA (CHA / Charisma & Influence)
  // ==========================================
  {
    id: 'cat_cha_1',
    title: 'Escucha de Comandante: Conversación Atenta Sin Interrumpir',
    description: 'Prestar 100% de atención al interlocutor sin consultar el teléfono ni interrumpir.',
    category: 'habit',
    rank: Rank.D,
    targetCount: 1,
    unit: 'sesión',
    attributeTarget: 'CHA',
    icon: 'hearing',
    xpReward: 200,
    goldReward: 150,
    essenceReward: 5,
  },
  {
    id: 'cat_cha_2',
    title: 'Reconocimiento de Mérito: Elogio Sincero y Detallado',
    description: 'Agradecer y destacar el trabajo bien hecho de un compañero o familiar.',
    category: 'habit',
    rank: Rank.E,
    targetCount: 1,
    unit: 'elogio',
    attributeTarget: 'CHA',
    icon: 'military_tech',
    xpReward: 150,
    goldReward: 100,
    essenceReward: 4,
  },
  {
    id: 'cat_cha_3',
    title: 'Alianza Estratégica: Reconectar con un Aliado Clave',
    description: 'Enviar un mensaje cordial a un colega o mentor para aportar valor desinteresado.',
    category: 'habit',
    rank: Rank.C,
    targetCount: 1,
    unit: 'contacto',
    attributeTarget: 'CHA',
    icon: 'handshake',
    xpReward: 250,
    goldReward: 190,
    essenceReward: 7,
  },
  {
    id: 'cat_cha_4',
    title: 'Voz Firme y Articulación: 10 Minutos de Ejercicios Vocales',
    description: 'Modular tono, ritmo y proyección para transmitir autoridad natural al hablar.',
    category: 'habit',
    rank: Rank.D,
    targetCount: 10,
    unit: 'minutos',
    attributeTarget: 'CHA',
    icon: 'record_voice_over',
    xpReward: 180,
    goldReward: 120,
    essenceReward: 5,
  },
  {
    id: 'cat_cha_5',
    title: 'Presentación Asertiva: Defender una Idea con Serenidad',
    description: 'Exponer tu punto de vista en una reunión o conversación con convicción y respeto.',
    category: 'discipline',
    rank: Rank.B,
    targetCount: 1,
    unit: 'intervención',
    attributeTarget: 'CHA',
    icon: 'campaign',
    xpReward: 350,
    goldReward: 270,
    essenceReward: 10,
  },

  // ==========================================
  // DISCIPLINA DE LA SOMBRA (DISCIPLINE / Absolute Focus)
  // ==========================================
  {
    id: 'cat_disc_1',
    title: 'Bloque Monacal de Deep Work: 90 Minutos de Enfoque Ininterrumpido',
    description: 'Una sola tarea prioritaria con notificaciones apagadas y cero ventanas secundarias.',
    category: 'discipline',
    rank: Rank.A,
    targetCount: 90,
    unit: 'minutos',
    attributeTarget: 'INT',
    icon: 'psychology_alt',
    xpReward: 600,
    goldReward: 500,
    essenceReward: 20,
    statPointsReward: 1,
  },
  {
    id: 'cat_disc_2',
    title: 'Ayuno Intermitente 16/8: Disciplina Metabólica',
    description: 'Completar 16 horas de ayuno calórico para activar autofagia celular y claridad mental.',
    category: 'discipline',
    rank: Rank.B,
    targetCount: 16,
    unit: 'horas',
    attributeTarget: 'VIT',
    icon: 'hourglass_empty',
    xpReward: 380,
    goldReward: 290,
    essenceReward: 11,
  },
  {
    id: 'cat_disc_3',
    title: 'Auditoría Nocturna del Cazador: Rendición de Cuentas',
    description: 'Evaluar objetivamente si el día fue una victoria o una derrota frente al Sistema.',
    category: 'discipline',
    rank: Rank.E,
    targetCount: 1,
    unit: 'auditoría',
    attributeTarget: 'WIS',
    icon: 'fact_check',
    xpReward: 160,
    goldReward: 110,
    essenceReward: 4,
  },
  {
    id: 'cat_disc_4',
    title: 'Primero lo Más Difícil: Derrotar al Monstruo Jefe a Primera Hora',
    description: 'Completar la tarea más pesada o incómoda antes de las 11:00 AM.',
    category: 'discipline',
    rank: Rank.B,
    targetCount: 1,
    unit: 'tarea crítica',
    attributeTarget: 'STR',
    icon: 'emoji_events',
    xpReward: 420,
    goldReward: 340,
    essenceReward: 12,
  },
  {
    id: 'cat_disc_5',
    title: 'Día Sin Quejas: Cero Lamentos Durante 24 Horas',
    description: 'Si surge un obstáculo, el cazador formula exclusivamente soluciones prácticas.',
    category: 'discipline',
    rank: Rank.A,
    targetCount: 1,
    unit: 'día estoico',
    attributeTarget: 'WIS',
    icon: 'shield_moon',
    xpReward: 520,
    goldReward: 410,
    essenceReward: 15,
    statPointsReward: 1,
  },
];

/**
 * Generates a randomized batch of diverse daily quests scaled to the player level.
 */
export function getRandomDailyQuests(
  count = 4,
  playerLevel = 1,
  existingTitles: string[] = []
): Omit<Quest, 'id' | 'completed' | 'createdAt'>[] {
  const existingSet = new Set(existingTitles.map((t) => t.trim().toLowerCase()));

  // Filter out already active quests
  const available = DAILY_QUEST_CATALOG.filter(
    (q) => !existingSet.has(q.title.trim().toLowerCase())
  );

  const pool = available.length >= count ? available : DAILY_QUEST_CATALOG;

  // Group by broad focus to guarantee diversity
  const groups: Record<string, CatalogQuest[]> = {
    fitness: pool.filter((q) => q.category === 'fitness'),
    intellect: pool.filter((q) => q.category === 'intellect'),
    health: pool.filter((q) => q.category === 'habit' || q.attributeTarget === 'VIT'),
    discipline: pool.filter((q) => q.category === 'discipline' || q.category === 'mindfulness'),
  };

  const selected: CatalogQuest[] = [];
  const groupKeys = Object.keys(groups);

  // Pick one from each primary group first
  groupKeys.forEach((key) => {
    const list = groups[key];
    if (list && list.length > 0 && selected.length < count) {
      const idx = Math.floor(Math.random() * list.length);
      selected.push(list[idx]);
    }
  });

  // Fill remaining slots randomly
  const remaining = pool.filter((q) => !selected.some((s) => s.id === q.id));
  const shuffled = [...remaining].sort(() => 0.5 - Math.random());

  while (selected.length < count && shuffled.length > 0) {
    selected.push(shuffled.pop()!);
  }

  // Level scaling multiplier for rewards
  const levelMultiplier = 1 + Math.min(2.5, (playerLevel - 1) * 0.05);

  return selected.map((item) => ({
    title: item.title,
    description: item.description,
    rank: item.rank,
    category: item.category,
    rewards: {
      xp: Math.round(item.xpReward * levelMultiplier),
      gold: Math.round(item.goldReward * levelMultiplier),
      essenceStones: item.essenceReward,
      statPoints: item.statPointsReward,
    },
    isDaily: true,
    targetCount: item.targetCount,
    currentCount: 0,
    unit: item.unit,
  }));
}

/**
 * Returns a single random quest from the catalog.
 */
export function getRandomSingleQuest(
  playerLevel = 1,
  existingTitles: string[] = []
): Omit<Quest, 'id' | 'completed' | 'createdAt'> {
  const quests = getRandomDailyQuests(1, playerLevel, existingTitles);
  return quests[0];
}
